gradle.properties

I set the version number to **2.1.0-SNAPSHOT**, it will allow us to publish unstable versions _if needed_.

Prepare 2.1.0

---

README.md
gradle.properties
library-no-op/src/main/java/com/readystatesoftware/chuck/api/Chuck.java

- Add `Chuck.init(Context)` to no-op library
- Bump to 2.0.4

[FIX] no-op Chuck#init method is missing

---

library/src/main/java/com/chuckerteam/chucker/api/internal/data/entity/HttpTransaction.kt

Fixes #37 
Making sure the path is displayed correctly if the query segment is null.
| -- | -- |
| ![Screenshot_1554058851](https://user-images.githubusercontent.com/3001957/55293632-cb574600-53f8-11e9-95b2-25064081b940.png) | ![Screenshot_1554058833](https://user-images.githubusercontent.com/3001957/55293633-cf836380-53f8-11e9-8cda-3214dba0a6c0.png) |

Do not display URL Query if the query is null

---

library/src/main/java/com/chuckerteam/chucker/api/internal/support/FormatUtils.java

This PR replicates https://github.com/jgilfelt/chuck/pull/84
The fix will prevent the library from loading external resources when parsing an XML from a response body.

Prevent potential XXE attacks from XML formatting

---

README.md
gradle.properties

As discussed at AndroidMakers, let's move both artifacts to JitPack.
This makes easier for everyone to release new version (Just `git tag`) and we don't have GPG keys to handle etc.
I think we just need to tag `2.0.4` as it was never tagged so is not available on JitPack.

Switch Release Artifact to JitPack

---

README.md

Looks like having the dependency coordinates all lowercase is not working.
Updating to use the one copy-pasted from Jitpack.

Make sure dependency examples have the proper case

---

library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt

This was causing the library being harder to use from Java,
as you would need to provide all the parameters to initialise a
ChuckerInterceptor.

Add missing @JvmOverload on the ChuckerInterceptor

---

build.gradle
detekt-config.yml
library/build.gradle
library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/main/java/com/chuckerteam/chucker/api/internal/support/OkHttpUtils.kt
library/src/test/java/com/chuckerteam/chucker/api/internal/support/OkHttpUtilsTest.kt
library/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

Chucker was using one methods from the aforementioned package.
Those methods are risky to use as they may be broken between releases
and I'm cleaning them up.
Specifically the method `hasBody` has now been moved to an extension
function inside our internal package. This will make easier to migrate
to OkHttp 4.x as the above method has been removed.
Fixes #52
Thanks @ZacSweers for the report <3

Remove usage of methods from okhttp3.internal

---

gradle.properties

Bumping the version to `-alpha2` so users can benefit of the OkHttp4 fixes

Prepare 3.0.0-alpha2

---

library/src/main/java/com/chuckerteam/chucker/api/internal/data/repository/RepositoryProvider.kt
library/src/main/java/com/chuckerteam/chucker/api/internal/ui/BaseChuckerActivity.java

Clicking the notification after the app would have been closed or killed would trigger a crash because the repositories were only initialized when creating the Intercaptor.
Fixes #68

Fix crash when clicking notification

---

library/src/main/java/com/chuckerteam/chucker/api/internal/ui/MainActivity.java

Change manual checks to `ApplicationInfo#loadLabel()` call.
Remove unnecessary conversion to String.
Fixes #73

Fix application name retrieval.

---

library-no-op/src/main/java/com/chuckerteam/chucker/api/ChuckerCollector.kt
library/src/main/java/com/chuckerteam/chucker/api/ChuckerCollector.kt
sample/src/main/java/com/chuckerteam/chucker/sample/MainActivity.kt

This PR starts the process of hiding the `RetentionManager` in the public API by deprecating the existing method (with appropriate Javadoc) and internally it treats the `RetentionManager` as an implementation detail, so users would only need to supply a _retention period_ and the `ChuckCollector` manages an instance of it.  This means that the API effectively changes from
```kotlin
collector = ChuckCollector(this)
.showNotification(true)
.retentionManager(RetentionManager(this, ChuckCollector.Period.ONE_HOUR))
```
to
```kotlin
collector = ChuckCollector(this)
.showNotification(true)
.retentionPeriod(ChuckCollector.Period.ONE_HOUR)
```
I took a conservative approach (by deprecating the existing method) as I didn't know if you already had production usages of that piece of code.

Hide the RetentionManager in the API (Issue #31)

---

library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionPayloadFragment.kt

To avoid the formating of json or xml stalling the UI, the payload will be loaded and formatted in an async task instead.
Fixes #55

Fetch payload in AsyncTask

---

build.gradle
library/src/main/java/com/chuckerteam/chucker/api/internal/ui/HomePageAdapter.java
library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionActivity.java
sample/build.gradle
sample/src/main/AndroidManifest.xml
sample/src/main/java/com/chuckerteam/chucker/sample/SampleApplication.java

- AndroidX migration
- [LeakCanary](https://github.com/square/leakcanary) reports some memory leaks on Transaction*Fragment's adapter. I think the cause is that viewpager adapter holds child fragment's reference in arraylist. So I've changed some codes.

LeakCanary memory leak report

---

library/src/main/java/com/chuckerteam/chucker/api/internal/data/entity/HttpTransaction.kt
library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionPayloadFragment.kt

Apparently #72 and #67 interacted in a way that created a bug in image parsing.
The response image is loaded now both for request and response. It should be loaded only for the response:
| Request | Response |
| -- | -- |
| ![Screenshot_1565253248](https://user-images.githubusercontent.com/3001957/62688517-4f35c600-b9c9-11e9-8c4d-7a551a6d743a.png) | ![Screenshot_1565253250](https://user-images.githubusercontent.com/3001957/62688521-51982000-b9c9-11e9-8f7d-1225a748e8f6.png) |

Fix image being loaded twice for request and response

---

library/src/main/java/com/chuckerteam/chucker/api/internal/support/JsonConvertor.java
library/src/test/java/com/chuckerteam/chucker/api/internal/support/FormatUtilsTest.kt

Looks like when we're parsing the JSON body for pretty printing we're actually omitting nulls.
This PR fixes this plus I've attached some JUnit tests to make sure all works fine.
Fixes #80

Fix for null values being omitted in the parsed body

---

library/src/main/res/values/strings.xml

Fixes lint warning `warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.`
This warning is also propagated to app using Chucker.

Add positions to string formatting placeholders

---

library/src/main/java/com/chuckerteam/chucker/api/internal/support/NotificationHelper.java

Fixing the count of transactions that is shown on the notification.
Apparently this code:
```
if (transaction.getStatus() == HttpTransaction.Status.Requested) {
transactionCount++;
}
```
was causing a miscount of the seen HTTP calls. If a call is already `.Completed` by the time it gets reported to Chucker, the `transactionCount` variable won't be updated.
I'm replacing the simple counter with an `HashSet` of transaction IDs. This will allow us to precisely count how many HTTP Request/Response we saw and report it in the notification number.
Fixes #84

Improving counting of seen transactions in notification message

---

README.md

One of the two dependency was lowercase, I'm fixing it.

Fixed typo in the Chucker Gradle implementation string

---

library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt

It prevents the SQLiteBlobTooBigException that would happen when downloading big images.
Fixes #94

Limit size of binary image to 1 million bytes.

---

CHANGELOG.md
README.md
gradle.properties

Since we had a regression on `3.0.0` related to images being bigger than 1Mb, it's probably worth to do a point release here.

Prepare 3.0.1 stable

---

build.gradle
gradle/kotlin-static-analysis.gradle
library-no-op/src/main/java/com/chuckerteam/chucker/api/Chucker.kt
library-no-op/src/main/java/com/chuckerteam/chucker/api/ChuckerCollector.kt
library-no-op/src/main/java/com/chuckerteam/chucker/api/RetentionManager.kt
sample/src/main/java/com/chuckerteam/chucker/sample/MainActivity.kt

Given that detekt is now at stable and at `1.0.1`, makes sense to keep it up to date.

Detekt to 1.0.1

---

library/src/main/res/layout/chucker_fragment_transaction_payload.xml

This will improve readability especially of long responses.
| --- | --- |
| ![Screenshot_1568838443](https://user-images.githubusercontent.com/3001957/65184072-1a576d00-da65-11e9-8375-d66b0b67b7be.png) | ![Screenshot_1568838342](https://user-images.githubusercontent.com/3001957/65184091-217e7b00-da65-11e9-9125-1d609fb97c8f.png) |
Fixes #115

Update the request/response body to use a monospace font

---

library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorListFragment.java
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionListFragment.java
library/src/main/res/layout/chucker_fragment_error_list.xml
library/src/main/res/layout/chucker_fragment_transaction_list.xml
library/src/main/res/values/strings.xml

When the network tab or errors tab is empty, will display a short explanation tab and a direct link to the chucker README file.
Fixes #106

Display explanation text on tabs if empty

---

library/src/main/res/layout/chucker_activity_error.xml
library/src/main/res/layout/chucker_activity_main.xml
library/src/main/res/layout/chucker_activity_transaction.xml
library/src/main/res/layout/chucker_fragment_error_list.xml
library/src/main/res/layout/chucker_fragment_transaction_list.xml
library/src/main/res/layout/chucker_fragment_transaction_overview.xml
library/src/main/res/layout/chucker_fragment_transaction_payload.xml
library/src/main/res/layout/chucker_list_item_error.xml
library/src/main/res/layout/chucker_list_item_transaction.xml

Developing full support for RTL would require to adapt all
the ViewPagers/TabLayouts to work correctly. I'm currently
fixing all the layouts to LTR and we'll wait for ViewPager2
to provide full RTL support.
| List | Transaction |
| -- | -- | 
| ![Screenshot_1568907113](https://user-images.githubusercontent.com/3001957/65258579-6f49c080-db03-11e9-880b-90f1a8e64eff.png) | ![Screenshot_1568907116](https://user-images.githubusercontent.com/3001957/65258618-77096500-db03-11e9-82cd-e8e5c81d8a9e.png) |
Fixes #117

Force all layouts to be LTR

---

library-no-op/src/main/java/com/chuckerteam/chucker/api/Chucker.kt

Java Apps references the SCREEN_HTTP/SCREEN_ERROR constants differently when the const keyword is added/removed
This fixes the inconsistency between library and library-no-op

Fix inconsistency when referencing screen constants from Java

---

library/src/main/java/com/chuckerteam/chucker/internal/ui/MainActivity.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorActivity.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionActivity.kt

Minor set of changes to make a unified way of how `TransactionActivity` and `ErrorActivity` start, since after recent merges these operations looked quite different.

Unification for activities start

---

library/src/main/java/com/chuckerteam/chucker/internal/support/NotificationHelper.java
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionActivity.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPagerAdapter.kt

On Android Q notifications won't appear in status bar and it might confuse devs, who expect to see notifications as soon as network activity happens. Above you can find screenshots of such issue when notifications present only in shade, while status bar is empty.
Changed importance from `IMPORTANCE_LOW` to `IMPORTANCE_DEFAULT` in notification channel properties.

Fix notification importance for Android Q

---

library/src/main/java/com/chuckerteam/chucker/internal/support/ClearDatabaseService.kt

Looks like we just have an unused variable that can definitely go

Remove unused variable in ClearDatabaseService

---

library/src/main/java/com/chuckerteam/chucker/internal/support/NotificationHelper.kt

Basically, this PR is just a duplicate of #144.
It appears that after another merged PR `NotificationsHelper.java` file with my fix was deleted and replaced by its Kotlin version. So I am just restoring that from #144 .
However, I also found that one of functions have `@JvmStatic` annotation, while not being called from Java class anywhere in the project. So removed this annotation.

Another fix for notifications in Q

---

library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransaction.kt

Fix for a small issue with dates formatting reported in #158 
Changed getters for `requestDateString` and `responseDateString` to create new `Date` object with `Long` value store in correspondent field of transaction.
I think that we can update `HttpTransaction` model to use `Date` instead of `Long` for `requestDate` and `responseDate`. For now decided just make explicit formatting, but we can get rid of it.
Fixes #158

Add date formatting for requestDate and responseDate

---

library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt

My logcat is being spammed with strictmode warnings:
```
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
java.lang.Throwable: Explicit termination method 'end' not called
at dalvik.system.CloseGuard.open(CloseGuard.java:223)
at java.util.zip.Inflater.<init>(Inflater.java:106)
at okio.GzipSource.<init>(GzipSource.kt:44)
at com.chuckerteam.chucker.api.internal.support.IOUtils.getNativeSource(IOUtils.java:67)
at com.chuckerteam.chucker.api.ChuckerInterceptor.getNativeSource(ChuckerInterceptor.kt:162)
at com.chuckerteam.chucker.api.ChuckerInterceptor.intercept(ChuckerInterceptor.kt:112)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
at …
```

Close the native source.

---

library/proguard-rules.pro
library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorListFragment.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionListFragment.kt
library/src/main/res/layout/chucker_fragment_error_list.xml
library/src/main/res/layout/chucker_fragment_transaction_list.xml

Fixes #163
Added full path to `LinearLayoutManager` in xml to avoid problems like users mentioned in the linked issue.
Also, removed redundant ProGuard exception, since Chucker has no Support libs anymore.
Get a confirmation from users from #163 that everything works fine now.

Fix issue with LinearLayoutManager after code minification

---

library-no-op/build.gradle
library/build.gradle

Attempt to fix #134 by passing a compiler flag to prevent name clashing with the `META-INF/library_release.kotlin_module` filename.
Fixes #134
Adding a Kotlin compiler flag inside both `library` and `library-no-op`.
Nop
Ideally we could publish the artifact locally and check that the file is properly named inside the Jar

Pass the -module-name Kotlin Compiler flag

---

gradle/gradle-mvn-push.gradle

Current POM on bintray: https://bintray.com/olivierperez/Chucker/download_file?file_path=fr%2Fo80%2Fchucker%2Flibrary%2F2.0.4%2Flibrary-2.0.4.pom contains `  <name>null:library</name>`
GROUP property value was assigned to root project group but pom was generated from library projects (which have empty groups).
None
No
Check `<name>` content in `library(no-op)/build/poms/pom-default.xml` file. Not sure which gradle task exactly creates this file. It needs to be some dependency of `bintrayUpload`.

Fix "null" prefix in POM name

---

build.gradle

Looks like I accidentally included an unintended line when merging #145 with `develop`. Here the cleanup. Thanks @vbuberen for spotting the issue.

Remove stale support-lib-version from gradle file

---

library-no-op/src/main/java/com/chuckerteam/chucker/api/Chucker.kt
library/src/main/java/com/chuckerteam/chucker/api/Chucker.kt
library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransaction.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransactionTuple.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/repository/RepositoryProvider.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/room/ChuckerDatabase.kt

Most of the code is already migrated to Kotlin, which means we don't need `@JvmStatic` annotated functions anymore. Since this annotation generates additional methods during compilation, I believe Chucker should get rid of it.
Also, some code parts 
- Removed @JvmStatic annotations almost everywhere (a few usages left)
- Used String interpolation in a few places to support switching to unified code style across the project
- Added a few `const` keywords in database `companion object`
Remove other `@JvmStatic` annotations when Kotlinification of `FormatUtils` class will be merged into `develop`

Minor code cleanup

---

library/src/main/java/com/chuckerteam/chucker/internal/support/SearchHighlightUtil.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadAdapter.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
library/src/main/res/layout/chucker_fragment_transaction_payload.xml
library/src/main/res/layout/chucker_transaction_item_body_line.xml
library/src/main/res/layout/chucker_transaction_item_headers.xml
library/src/main/res/layout/chucker_transaction_item_image.xml
library/src/main/res/values/dimens.xml
library/src/main/res/values/strings.xml

Currently Chucker UI hangs when the HTTP request/response body is too
big. The issue is caused by having to put a bunch of text inside a
single TextView.
This commit refactors the request/response body screen to use a
RecyclerView to load single lines. In this way the UI is much smoother
and the experience is generally better.
Fixes #82
Only changes inside `.internal` so no breaking changes on the API.
On the other hand there are a couple of drawbacks:
- Text in the body is selectable only line by line.
- Search in the body works only line by line.
- Response/Request screen are not inside a `NestedScrollView` anymore (as this had major performance drawbacks) 
Ideally we should extend the sample app with a single call to https://data.cityofnewyork.us/api/views/kku6-nxdu/rows.json or to …

Fixing handling of big body payloads

---

library/build.gradle
library/src/main/java/com/chuckerteam/chucker/internal/support/ChuckerCrashHandler.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/FormatUtils.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/IOUtils.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/LiveDataUtils.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/NotificationHelper.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/OkHttpUtils.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/SearchHighlightUtil.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/BaseChuckerActivity.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/MainActivity.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionActivity.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionOverviewFragment.kt

Fix for #179 
- Updated visibility modifiers
- Changed fun for starting TransactionActivity, since after merging PR with `ViewModel` this fun was reverted to state before #137 
- Fixed typo, which appeared after #146 
- Replaced deprecated calls for JsonParser

Visibility fix for internal members

---

.travis.yml

Current CI process can be optimised. For example, I am always annoyed when I have to wait till build passes only to find out that ktLint or Detekt finds some issues and fails the whole pipeline.
Since ktLint and Detekt don't require the build result we can put them first in the pipeline to follow `Fail fast` principle and provide contributors faster feedback on their code quality status.
For example, locally ktLint task takes only 4 seconds for me, so it is much better than waiting some time till build finishes.
Changed the order of commands in Travis CI config.
Going to do further process optimisations to speed up builds and do some fine tuning for used tools

CI pipeline optimisation

---

library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorActivity.kt

`ErrorActivity` should extend `BaseChuckerActivity` as well, since that base class is used for checks whenever the app is in background/foreground and, correspondingly, for firing/not firing pushes.
Changed only one line in `ErrorActivity` declaration.
Consider using `ActivityLifecycleCallbacks` for such cases.

Fix for wrong class used for extending in ErrorActivity

---

README.md
library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt

When using ```ChuckerInterceptor```, you are forced to used a ```MutableSet``` for ```headersToRedact``` parameter.
It is better to mask the true type of ```headersToRedact```  and expose a simple ```Set```.
I change ```ChuckerInterceptor``` to accept a simple ```Set```.
I also upgrade *README* which was correct for this parameter.

Mask true type of headersToRedact and update documentation

---

library/src/main/res/values/public.xml

Before:
After:
After fixing visibility for internal classes I decided to also try to make all the resources we have (like strings, drawables, values, etc.) private, so users won't see them in autocomplete suggestions.
According to https://developer.android.com/studio/projects/android-library#PrivateResources
all we need to do is to create some public resource (might be even empty), so others are marked as private in final `aar`.
Unfortunately, this approach won't work when the library added as module, like we have in sample app, so wasn't able to check locally.
Added a single resource marked as public.
Nothing wrong expected.
Try to get snapshot from Jitpack as `com.github.ChuckerTeam:Chucker:fix~hide_resources-SNAPSHOT` and try to check autocomplete in the app using this dependency.

Hide library resources

---

README.md
library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt

After merging #181 I decided to review some of the code, which works with headers and simplify it a little bit both in terms of usage and code quality.
During this work I found out that comparison of headers in `filterHeaders` was case-sensitive, while [the official HTTP standard](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) states that header field names are case-insensitive. So, it means that the library had a bug, which I also fixed here.
- Changed parameter type in `redactHeader()` function to accept `vararg` (note, that nothing changes for existing users).
- Replaced headers comparison with case-insensitive alternative
- Updated Readme and `ChuckerInterceptor` documentation to match changes.
No

Headers redaction refactoring

---

README.md

Before:
After:
I believe that library version, build status and licence info are the most important of badges to the majority of users, so we should put them first.
Changed order of badges in README.md

Change order of badge

---

library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt

Fixing a potential `IllegalStateException: closed` if other OkHttp Interceptors are accessing the Response Buffer. The bug was introduced in #165. See the discussion in #192 for further context.
Let's close the buffer early upfront rather than opening/closing it directly.
Fixes #192

Clone the Response Buffer rather than using it directly

---

library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/IOUtils.kt
sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt
sample/src/main/res/xml/network_security_config.xml

Fixes a bug introduce by me in #198, when implementing clone of the `okio.Buffer` from the HTTP Response.
Looks like the problem on our end what that we were using `ChuckerInterceptor` as first interceptors, so the Sample App showed valid results. Switching order of the interceptors showed that responses are `null` and the approach followed for the `.clone()` was not correct. I reimplemented it following the `HttpLoggingInterceptor` body.
Remove the fix I applied on `ChuckerInterceptor` and keep only the changes I applied in the sample app. It should break and show `null` in the response body.
Fixes #203
Closes #205

Fix for Empty Response Body and 0 Content Lenght

---

library/src/main/res/layout/chucker_activity_transaction.xml
library/src/main/res/layout/chucker_fragment_transaction_payload.xml

| --- | --- |
|![toolbar_before](https://user-images.githubusercontent.com/13467769/73213069-388e5180-4158-11ea-9d87-828d2d58ad0c.gif) |![toolbar_after](https://user-images.githubusercontent.com/13467769/73213081-3b894200-4158-11ea-9e35-11bf7a9addee.gif) |
Both in Chuck and Chucker I was always seeing the same bug where switching from `Overview` to `Response` tab made the toolbar collapse. Scrolling the content won't return the toolbar and user has to do a downwards scroll on `TabLayout` to bring the toolbar back. I believe that for this screen there is no need in toolbar hiding, so remove scroll flags from it.
- Removed scroll flags from `Toolbar` in `TransactionActivity`
- Fixed the position of `ProgressBar` in `Response` tab.

Fix for redundant toolbar collapsing

---

gradle.properties
library/src/main/res/layout/chucker_activity_transaction.xml
library/src/main/res/layout/chucker_fragment_transaction_payload.xml

During 3.1.1 release preparation version name and code weren't updated. 
This PR resolves that issue, so the tag 3.1.1 can be recreated with proper versions.
- Updated `gradle.properties` #211
- Minor fix for collapsing toolbar issue #210 
Recreate tag `3.1.1` and republish it.

Fix for version name

---

library/src/main/java/com/chuckerteam/chucker/internal/support/FormatUtils.kt

| --- | --- |
| ![Before](https://user-images.githubusercontent.com/13467769/73309368-c2a6ea80-422a-11ea-944c-25d4bf2c192f.png) | ![After](https://user-images.githubusercontent.com/13467769/73309373-c5094480-422a-11ea-8c3f-d07ed242ab72.png) |
It seems that in `3.1.0` and `3.1.1` respectively we have a bug with generated curl share command.
It happens due to incorrect string interpolation usage (see attached screenshots).
- Added curly braces into all required calls in `getShareCurlCommand()`

Fix for curl command

---

library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionViewModel.kt

*Why did you change something? Is there an [issue](https://github.com/ChuckerTeam/chucker/issues) to link here? Or an extarnal link?*
https://github.com/ChuckerTeam/chucker/issues/217
*Which code did you change? How?*
`TransactionViewModelFactory` uses now ViewModel's constructor instead of obtaining it via reflection.
*Is there something breaking in the API? Any class or method signature changed?*
No. Only internal API changes.
*Is there a special case to test your changes?*
Run a sample app that is minified with R8 in full mode. It will crash when one wants to open Chucker.
*Do we have to plan something else after the merge?*
No.

Fix R8 minification crash on TransactionViewModel creation.

---

library/src/main/java/com/chuckerteam/chucker/internal/support/ClearDatabaseService.kt

Found a case when Chucker would crash, but since it is incorporated into other apps the dialog with `[App name] stopped` appears and might confuse devs. This happens if the app with Chucker is killed (for example, via swiping from recents screen) and user tries to click `Clear` in Chucker notification. Since the app is killed, so as `RepositoryProvider` and, thus, we get crash, since both `transaction()` and `throwable()` functions use `checkNonNull()`.
Added call to `initialize()`, so clear action will always have an instance to work with.
To get crash on current `develop` version get some notifications, kill the app, try to click on `Clear` in network or throwable notifications.

Fix clear action crash when application is dead

---

library/src/main/java/com/chuckerteam/chucker/internal/support/NotificationHelper.kt

Fix, which should protect from issues, like #168 in `NotificationHelper`. Checks for `transaction` in `transactionBuffer` being `null` should protect from cases described in the mentioned issue.
Add explicit check for `null` value in `transactionBuffer`.

Fix for NPE in NotificationHelper

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE

| Bug | PR |
| --- | --- |
| ![bug](https://user-images.githubusercontent.com/13467769/74149662-f6ade280-4c10-11ea-8b5c-def39c5685c9.png) | ![feature_request](https://user-images.githubusercontent.com/13467769/74149666-f877a600-4c10-11ea-9a26-561b2fcc34db.png)
| PR |
|![PR](https://user-images.githubusercontent.com/13467769/74149667-f9103c80-4c10-11ea-864e-ea489c1ae06c.png)|
Wanted to just fix the typo in PR template, but ended up with updates to issues templates as well.
Now text in templates is marked as comment, so it won't appear in the message after editing.
- Fixed typo in `external` word in PR template.
- Switched to comments instead of regular text in all templates.
- Updated some emojis 😄

Update Github templates

---

library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionAdapter.kt

Currently Chucker uses own constants to check HTTP status codes.
In Android we already have these constants, so why don't we switch to them instead of defining our constants?
Switched to `HttpsURLConnection` constants for status code checks.

Switch to platform defined HTTP code constants

---

.github/ISSUE_TEMPLATE/feature_request.md

We might have users who have no experience with markdown, so they might have issues with selection in `Do you want to develop this feature yourself`. To address such cases I decided to add some basic instruction.
Added a comment into the `feature request` template.

Add instruction for checkbox selection

---

library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpHeader.kt

I get this exception in `HttpTransaction.setRequestHeaders` when DexGuard is enabled:
```
java.lang.IllegalArgumentException: class o.bwy declares multiple JSON fields named ι
```
Mapping:
```
com.chuckerteam.chucker.api.internal.data.entity.HttpHeader -> o.bwy:
java.lang.String name -> ι
java.lang.String value -> Ι
```
Annotated fields in `HttpHeader` with `@SerializedName` so that Gson would know how to serialize that class when it's obfuscated.

Fix HttpHeader serialization when obfuscation is enabled

---

.github/workflows/gradle-wrapper-validation.yml

Let's add a simple GH action to validate the Gradle Wrapper just to play on the safe side.

Add Action to validate the Gradle Wrapper

---

build.gradle
library/build.gradle
library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransaction.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/repository/HttpTransactionDatabaseRepository.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/repository/RecordedThrowableDatabaseRepository.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/LiveDataUtils.kt
library/src/test/java/com/chuckerteam/chucker/TestUtils.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/LiveDataDistinctUntilChangedTest.kt

There is an open issue. #244
DB queries which observe entities by their IDs now check beforehand is something changed before emitting data downstream.
This cannot be done on DB level as SQL emissions happen whenever table is changed (https://sqlite.org/lang_createtrigger.html).
One unpleasant change is custom `distinctUntilChanged()` `LiveData` extensions that accepts an executor on which it performs computation. It is needed as in our case data that is being compared can have long comparison computation (requests and responses), which would result in dropped frames.
Ideally `Flow` or Rx would be used to avoid this `LiveData` restriction.
Not blocking but there will be conflicts with https://github.com/ChuckerTeam/chucker/pull/233 due to `LiveData` extensions. I would suggest merging this …

Do not refresh transaction when it is not being affected.

---

library/src/main/java/com/chuckerteam/chucker/internal/support/SearchHighlightUtil.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadAdapter.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt

Found some issues with response body search, like mentioned in #254 and #255.
Also, it seems not optimal that Chucker performs search even when there is only one symbol in the search fields. To avoid redundant work I decided to update the logic to require more than 1 symbol.
- Closed #254 by switching from operator function `in` to `contains` with explicit declaration of case ingoring.
- Closed #255 by invalidating options menu after AsyncTask finishes transaction loading.
- Added a requirement to input more than 1 symbol to perform search.
Nothing breaking is expected
Just try to search something :)

Response search fixes

---

library/build.gradle
library/src/main/java/com/chuckerteam/chucker/internal/data/entity/RecordedThrowable.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/entity/RecordedThrowableTuple.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/MainActivity.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorActivity.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorAdapter.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/error/ErrorListFragment.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionActivity.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionAdapter.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionListFragment.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionOverviewFragment.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadAdapter.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
library/src/main/res/layout/chucker_activity_error.xml
library/src/main/res/layout/chucker_activity_main.xml
library/src/main/res/layout/chucker_activity_transaction.xml
library/src/main/res/layout/chucker_fragment_error_list.xml
library/src/main/res/layout/chucker_fragment_transaction_list.xml
library/src/main/res/layout/chucker_fragment_transaction_overview.xml
library/src/main/res/layout/chucker_fragment_transaction_payload.xml
library/src/main/res/layout/chucker_list_item_error.xml
library/src/main/res/layout/chucker_list_item_transaction.xml
library/src/main/res/layout/chucker_transaction_item_body_line.xml
library/src/main/res/layout/chucker_transaction_item_headers.xml
library/src/main/res/layout/chucker_transaction_item_image.xml
library/src/main/res/values/strings.xml

Chucker relied on `findViewById` stuff for quite a long time. Since [ViewBinding](https://developer.android.com/topic/libraries/view-binding) is officially released, I believe we should switch to it to make library code more concise and robust.
- Enabled `ViewBinding` in `build.gradle`.
- Switched all Activities, Fragments and Adapters to use `ViewBinding`.
- Removed some boilerplate, like duplicate of `onTransactionItemClickListener()`.
- Fixed link to tutorial, which became invalid after recent resources renaming.
Just run it.

Switch views to ViewBinding

---

build.gradle

Another attempt to update targetSDK in Chucker. Since we migrated from Travis, I expect no issues with licences. Also updated Kotlin version.
- Bumped targetSDK to 29
- Updated Kotlin plugin version to 1.3.70

Update targetSDK and Kotlin

---

.github/workflows/gradle-wrapper-validation.yml
.github/workflows/pre-merge.yaml

When first PR with GH Actions was created I saw that builds happen for every single action, be it push or pull request. So it seems that we are ending up with too much redundant work.
According to [this thread ](https://github.community/t5/GitHub-Actions/Github-actions-Cancel-redundant-builds/td-p/29549) Github has no native solution for this issue.
In that thread I also saw a few 3rd party actions and decided to test one of them.
- Added https://github.com/marketplace/actions/gh-actions-stale-run-canceller to test auto cancelling
If it works, I will add this step into the main workflow as well.

Add stale builds canceller

---

library/src/main/res/layout/chucker_fragment_transaction_payload.xml
library/src/main/res/layout/chucker_transaction_item_headers.xml

Before
After
There was a small UI issue with no margin/padding for `body_item` when no headers present in request/response (check the attached screenshots). It happened because only header item had margins.
Updated margins and paddings for transaction payload `RecyclerView` and for `item_header`

Margin fix for transaction payload

---

README.md
library-no-op/build.gradle
library-no-op/src/main/java/com/chuckerteam/chucker/api/Chucker.kt
library-no-op/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library-no-op/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
library/src/main/java/com/chuckerteam/chucker/api/Chucker.kt
library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt

There is an open issue that I declared to do - #266.
I added to the public API a header that allows to skip interception. `ChuckerInterceptor` respects this header and does not process requests if ordered not to do so. It also strips out this header before passing it down the chain.
Kind of, but not really. If someone in the past used a header like `Skip-Chucker-Interceptor` it would be no longer passed to the server. It would also skip Chucker processing if set to `true`.
Unit tests are written. I don't think there is a point in adding anything to the `HttpBinApi`.
Closes #266

Add selective interception.

---

library/src/test/java/com/chuckerteam/chucker/internal/support/FormatUtilsSharedTextTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/FormatUtilsTest.kt

Tests
- refactor FromatUtilsSharedText: move common parts to method
- change name of two xml tests in FormatUtilsTest to be consistent with other tests in this class
https://github.com/ChuckerTeam/chucker/pull/281
No

format utils test refactor

---

build.gradle
library/build.gradle
library/src/main/java/com/chuckerteam/chucker/api/ChuckerCollector.kt
library/src/main/java/com/chuckerteam/chucker/api/RetentionManager.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/repository/HttpTransactionDatabaseRepository.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/repository/HttpTransactionRepository.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/repository/RecordedThrowableDatabaseRepository.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/repository/RecordedThrowableRepository.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/room/HttpTransactionDao.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/room/RecordedThrowableDao.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/ClearDatabaseService.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/MainViewModel.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt

No UI change in the commit. Only functional Change.
The AsyncTask that is being used in Chucker library currently is going to be deprecated in android R. Also, AsyncTask is not that elegant solution to perform the background and CPU intensive work.
As we are leveraging all the functions of kotlin, this one is another addition to it.
I basically change the code where we can use kotlin coroutines which is the background threading work. So, I changed `TransactionPayloadFragment` , `HTTPTranasctionDatabaseRepository` and `RecordedThrowableRepository` .
No blocking PR
Nothing breaking in the API. No method signature change!
There's no need actually. As all unit tests are already passing.
But though if needed we can Unit test the AsyncTask related changed I migrated to Kotlin Coroutines.

Migrate to Kotlin Coroutines

---

library/src/main/java/com/chuckerteam/chucker/internal/support/JsonConverter.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/JsonConverterTest.kt

Removed redundant `FieldNamingPolicy` and `DateTypeAdapter` from Gson instance.
Why?
- Dates are not serialized or deserialized anywhere in the codebase.
- The field naming policy (`LOWER_CASE_WITH_UNDERSCORES`) is not in use.
- Changed `JsonConverter`. Removed redundant Gson configurations.
- Changed `JsonConverterTest`. Removed related test cases.
No. All test cases are passing. No method signature change.

Removed redundant Gson configurations

---

library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/TeeSourceTest.kt

There is an issue #287
`TeeSource` now reports partially read responses as failures. This way `ChuckerInterceptor` does not try to process them. The bytes are still available in the side channel file if in the future we'd like to process these bytes.
I also wrapped reading from file in a `try/catch` expression for a good measure because of the volatile nature of a phone storage.
No.
Unit tests are written. @oakkitten might confirm whether this fixes their issue using Chucker version from PR via JitPack.
Closes #287.

Properly handle unexhausted network responses

---

library/src/main/java/com/chuckerteam/chucker/internal/ui/throwable/ThrowableListFragment.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionListFragment.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt

While working on some other features I saw that all `RecyclerView`s in Chucker have `match_parent` sizes and don't change its height/width depending on its content. Based on that I added `setHasFixedSize(true)` to such lists.
- Added `setHasFixedSize(true)` to `RecyclerView` items.

Optimize RecyclerView items

---

build.gradle
gradle/kotlin-static-analysis.gradle
library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransaction.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransactionTuple.kt

Let's update Detekt before #298 
Seems like our detekt configuration was still using an older version (`1.4.0`). I've extracted that versions to use the version defined at the top level (same for `ktlint).
I've re-gerated the config file with `./gradlew detektGenerateConfig`. I've also copied over as we can potentially turn on more rules that are currently disabled by default.

Detekt to 1.7.4

---

library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt

Just found an extra `?.` that is not needed. This was reported as a compiler warning. I'm fixing it.

Removed Unnecessary safe call

---

library-no-op/build.gradle
library/build.gradle
library/src/main/res/menu/chucker_throwable.xml
library/src/main/res/menu/chucker_throwables_list.xml
library/src/main/res/menu/chucker_transaction.xml
library/src/main/res/menu/chucker_transactions_list.xml
sample/build.gradle
sample/src/main/AndroidManifest.xml
sample/src/main/res/values/colors.xml

We had several Lint warnings showing up during builds. I've fixed them plus raised Lint warnings to be errors so they will be reported as build failures.
Happy to discuss if we feel this is a too strict approach.
* Configured Lint to treat warnings as errors
* Add missing `roundIcon` directive on the Manifest
* Skipped failures of unused resources on some palette color.
* Fixed `showAsAction="always"` to `ifRoom`.
n/a
n/a
`./gradlew check` on the branch should be green now and no lint warnings should be shown.
n/a

Enforce Lint findings

---

library/src/main/java/com/chuckerteam/chucker/internal/ui/throwable/ThrowableListFragment.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionListFragment.kt
library/src/main/res/layout/chucker_activity_throwable.xml
library/src/main/res/layout/chucker_activity_transaction.xml
library/src/main/res/values/styles.xml

Continue switching from `AppCompat` to `MaterialComponents`. This time in-app dialogs were updated.
- Switched from `AlertDialog.Builder()` to `MaterialDialogBuilder()`.
- Updated one of styles to inherit `MaterialComponents` style.

Dialogs update

---

library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt

There is an open issue. #311
File resource containing response is now closed after Chucker reads from it.
No.
Apply `StrictMode.setVmPolicy(StrictMode.VmPolicy.Builder().detectAll().penaltyLog().build())` to the test application. It should no longer warn about opened resources.
Closes #311

Close response file when it is no longer needed.

---

library/src/main/java/com/chuckerteam/chucker/internal/support/FormatUtils.kt
library/src/main/res/values/strings.xml
library/src/test/java/com/chuckerteam/chucker/TestTransactionFactory.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/FormatUtilsSharedTextTest.kt

Before:
After:
During tests of export feature I found out that in case of empty body (happens both in request and in response) Chucker shows empty lines. So I decided to add some text to clearly indicate that body is empty for real, not because of some error.
Added a placeholder text for cases with empty body
Add more tests for different requests (with empty request/response bodies, etc.)

Add description for empty body items during export

---

library/src/main/res/layout/chucker_fragment_transaction_overview.xml

Screenshot from the same device (Nexus 5) as in the reported issue.
This fix closes #313 
To avoid issues with overlapping I added barriers to all items with long labels.
- Added barriers to items with long labels and constrained items placed below to this barriers.

Fix overlapping texts on Overview tab

---

.github/workflows/pre-merge.yaml

Currently we run our build in only on Gradle run and it makes hard to understand where the failure actually happened. Let's split it into separate steps.
Let's check if we have a major impact on the build time.
I expect some improvement due to the caching (not on the first run though). On the other side, running several separate gradle commands will lead to running configuration phase multiple times, as well as some duplicate work.

Split the CI steps between build and check

---

library/src/main/res/layout/chucker_list_item_transaction.xml

When trying to use on a TV device that only has a remote, you were not able to scroll.
In `chucker_list_item_transaction.xml` I added `android:focusable="true"` to the root ConstraintLayout
N/A
Only change is UI
Load the sample app on a TV device. You will now be able to scroll the list
Not right now, but I plan on adding more TV layout support.

Allow Transaction List Item to be focusable for use with TV apps

---

library/src/main/java/com/chuckerteam/chucker/internal/support/BitmapUtils.kt

Found out that during review of #320 I missed the fact that async `generate()` from Palette was used, which relies on `AsyncTaks` under the hood. We added coroutines to get rid of `AsyncTasks`, so I refactored the code to use only coroutines.
- Switched from asynchronous `generate` to synchronous.
- Forced `getLuminance()` to be called from `Dispatchers.Default` to not rely on the caller of `calculateLuminance()`

Refactor palette

---

library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransaction.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/FormatUtils.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/JsonConverter.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionViewModel.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/FormatUtilsTest.kt
sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinApi.kt
sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt

|Current|Formatted|
|-|-|
|![current](https://user-images.githubusercontent.com/54670603/79045408-3db55580-7c0b-11ea-8724-2e29d094fc8c.png)|![formatted](https://user-images.githubusercontent.com/54670603/79045412-40b04600-7c0b-11ea-97c0-f608407f54df.png)|
Reading encoded forms is nearly impossible, especially when dealing values have symbols in them. Unlike for XML and JSON requests, this does not simply pretty print the body and that may be undesired.

Format URL encoded forms

---

.github/workflows/pre-merge.yaml
build.gradle

I'm setting up a matrix on GH Actions for Kotlin version. This will allow us to have two parallel builds. One for Kotlin 1.3.x and another for the preview of 1.4
Relevant context here https://github.com/ChuckerTeam/chucker/pull/326#issuecomment-614462958
The Kotlin version is not set from an environment variable and has a fallback at the 1.3.x version so local builds are not impacted.

Setup a Kotlin version matrix on GH Actions

---

library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/PayloadType.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPagerAdapter.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt

This PR starts a process of sort of big rework how payload data is fetched to remove any business logic related things from fragments. To avoid bloated PR which is hard to review I will do a series of small when it is possible.
This time I changed approach to definition of required payload type for `TransactionPayloadFragment` from constants to a sealed class, which should help have less checks in place as well as be used by other classes in future.
- Switched from constants to sealed class in `TransactionPayloadFragment`.
To bring more context - I would like to move all payload processing from fragment and have everything in `ViewModel`, so fragment will just render data provided to it without any decisions.
With current state of things in the library it will be quite hard, but can be …

Update payload type definition

---

README.md
library-no-op/src/main/java/com/chuckerteam/chucker/api/Chucker.kt
library-no-op/src/main/java/com/chuckerteam/chucker/api/ChuckerCollector.kt
library/src/main/java/com/chuckerteam/chucker/api/Chucker.kt
library/src/main/java/com/chuckerteam/chucker/api/ChuckerCollector.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/NotificationHelper.kt

Since[ there is a plan](https://github.com/ChuckerTeam/chucker/issues/321#issuecomment-626138370) to remove Throwable catching functionality in `4.x` we need to prepare users to not introduce breaking changes right away. This PR adds proper deprecation messages, which should both inform and help to switch to valid functions.
- Added deprecation messages to public API.
Nothing special for testing. IDE should show suggestions if there is a replacement for deprecated function.

Deprecate Throwable related parts

---

_config.yml

This `_config.yaml` file is unused (was used for a legacy documentation website). We can safely remove it.

Remove unused _config.yaml

---

README.md

I'm updating the Maven Coordinates to be all lowercase. This is to smooth the support for publishing to Maven Central
I've tested the coordinates on the sample app at it works fine (both with a version and a SNAPSHOT release).
Related Issue #56 
I'll send out the machinery for publishing to Maven Central shortly after.

Update Maven Coordinates to be lowercase

---

gradle.properties

I'm bumping the local version to contains `-SNAPSHOT`.
This is needed as I'm preparing the setup to publish to Maven Central.
See #56 
Nothing really to test here.

Bump version name to contain -SNAPSHOT

---

.github/workflows/pre-merge.yaml

Looks like we don't need to use a third party action to set the `KOTLIN_VERSION` environment variable.
Moreover that action was firing a warning recently so I'd rather switch back to the default way of setting env variable.
If the build is ✅ , we're good to go.

Use job.env to set global environment variable

---

.github/workflows/pre-merge.yaml
.github/workflows/publish-release.yaml
.github/workflows/publish-snapshot.yaml
build.gradle
gradle.properties
gradle/gradle-mvn-push.gradle
library-no-op/build.gradle
library-no-op/gradle.properties
library/build.gradle
library/gradle.properties

Setup the repository to publish Chucker also on Maven Central.
The idea is to keep JitPack and Maven Central running side by side for some time.
Ideally we can publish the next version of Chucker (`3.3.0`) to Maven Central.
The publishing will be done by Github Actions in this way:
- Every merge to `develop` will publish a version to the `SNAPSHOT` repository.
- Every push of a new tag will publish a version to the staging repository (for releasing on the Central Repository).
Moreover I've added a step in the Pre Merge action that will trigger a Publishing on Maven Local (this will make sure we're able to publish correctly).
- Some general cleanup of the Gradle files (we had several unused/old properties).
- Moved the Dokka setup from libraries to the shared external script file.
Closes …

Setup publishing to Maven Central

---

.github/workflows/publish-release.yaml
.github/workflows/publish-snapshot.yaml
gradle/gradle-mvn-push.gradle

With the previous commit I accidentally broke the
CI builds coming from external forks. See #159 
Forks don't have access to this ORG secrets so
the publishToMavenLocal task was failing as the
environment variables were blank.
Moreover I'm also disabling the publishing workflow for forks.
If the build is ✅ , let's merge and rebase #159 on top of this.

Fix the CI setup for build on forks

---

.github/workflows/auto_rebase.yaml

It seems that Rebase workflow used old version of Checkout Action
Switched to `checkout@v2`
If this one works fine I will also update the same Action in Revert workflow.

Update rebase workflow to use new checkout

---

.github/workflows/auto_revert.yaml

Revert Action used old Checkout.
Switched to `checkout@v2`
Smilar to #348 
Going to open PRs in both Revert and Rebase repos to update their installation examples, so less people will copy outdated workflows.

Update Revert Action to use new Checkout

---

.github/workflows/publish-release.yaml
.github/workflows/publish-snapshot.yaml

The name of the artifact generated by the publish
workflows is accidentally swapped between release and snapshot.
I'm fixing it.

Fix wrong artifact name

---

.github/workflows/pre-merge.yaml
gradle/gradle-mvn-push.gradle

Let's split the `pre-merge` workflow into smaller jobs that can run in parallel.
This should significantly increase the speed of the CI and will provide immediate feedback on the PR on what failed.
If the CI is ✅, we're good to go.

Parallelise the pre-merge workflow

---

README.md

I'm updating the README to reflect #56 
I've also added a note in the Snapshot section mentioning that artifacts are still available both on Sonatype or JitPack.
The link of Maven Central:
https://search.maven.org/artifact/com.github.chuckerteam.chucker/library
might take some hours before showing meaningful results.

Update readme mentioning deployment to Maven Central

---

.github/workflows/pre-merge.yaml

Just keeping our build matrix up to date
Bumped the value for Kotlin 1.4 from `M1` to `M2`
Not much, if this PR is ✅ we're good to go

Update the build matrix to run on Kotlin 1.4-M2

---

build.gradle
library/build.gradle
library/src/main/java/com/chuckerteam/chucker/internal/data/repository/RepositoryProvider.kt
library/src/test/java/com/chuckerteam/chucker/internal/data/entity/HttpTransactionTupleTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/data/entity/TransactionTestUtils.kt
library/src/test/java/com/chuckerteam/chucker/internal/data/repository/HttpTransactionDatabaseRepositoryTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/data/repository/RepositoryProviderTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/data/room/HttpTransactionDaoTest.kt

Additional unit tests -
* HttpTransactionTupleTest
* HttpTransactionDatabaseRepositoryTest
* RepositoryProviderTest
* HttpTransactionDaoTest
To be able to utilize in-memory Room databases (that still require a `Context` to create) I added *Robolectric* to the test dependencies, and since that doesn't play nice with JUnit 5, added a clear dependency on the vintage test engine.

Improved unit test coverage

---

library/src/test/java/com/chuckerteam/chucker/internal/data/entity/TransactionTestUtils.kt

Seems like a merge clash between #359 and #354 broke the CI on master.
I've rerun `ktlintFormat` to fix the failure.

Reformat TransactionTestUtils

---

.github/workflows/pre-merge.yaml

It started from the need of invalidating Gradle caches when dependencies are updated. While doing this change I also updated Cache action and changed the way we declare caches.
- Added cache key based on hash of `build.gradle` file with dependencies versions.
- Updated Cache action to v2.
- Changed caches creation between jobs to re-use the same cache file.
- Added restore keys in case cache wasn't found by key.
No
Nothing special required.
Add Dependabot to update dependencies regularly.

Update work with Gradle cache

---

.github/dependabot.yml

It seems that I introduced an invalid YAML for Dependabot in #371. This PR fix the issue.
Also, I found out that currently automatic milestones assignment accepts only integers, so we can't add `3.3.0` in the config, but `9` (the number of `3.3.0`). Since `9` has no sense to most people it might be messed up and forgotten with time.
Aside from that I tried to add automatic reviewers assignment.
- Fixed indents in Dependabot config.
- Removed milestone assignment.
- Added reviewers assignment.
Nothing
Merge into `develop`

Fixes for Dependabot config

---

.github/dependabot.yml

Chucker uses Retrofit in its sample app. Since we still have minSDK 16 we can't update it.
To avoid redundant PR by Dependabot I added Retrofit into ignored list.
- Added Retrofit to ignored dependencies.

Add Retrofit to ignored list by Dependabot

---

build.gradle
library/build.gradle
library/src/main/java/com/chuckerteam/chucker/internal/ui/MainActivity.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/throwable/ThrowableActivity.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/throwable/ThrowableListFragment.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/throwable/ThrowableViewModel.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionActivity.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionListFragment.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionOverviewFragment.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionViewModel.kt

Due to how ViewModel objects were initialised Chucker had a bunch of crashes. 
This PR changes the way Chucker works with ViewModels and resolves a bunch of issues:
- Closes #364 
- Closes #366 
- Closes #367 
- Updated to Fragment 1.2.5 to use latest extensions required.
- Changed the declaration of ViewModel in Activity and Fragments.
No issues found so far.
For #364 follow the steps provided by @MiSikora 
For #366 and #367 enable `Don't keep activities` and try to share some transaction as curl.
Add `SavedStateHandle` to save search query in TransactionListFragment and search query in updated TransactionPayloadFragment search (isn't published yet).

Refactor viewmodels initialization to survive process death

---

.github/workflows/pre-merge.yaml

Kotlin 1.4-M3 was released yesterday. Let's update our build matrix to use it.
PR checks will tell ✅

Kotlin variant in pre-merge to 1.4-M3

---

library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/TeeSourceTest.kt

There is an open issue - #370.
I mostly worked on `TeeSource` and implemented `Callback`. Callers are now informed of finished byte processing whenever an upstream source is closed and now they are responsible for handling any data corruption that might have occurred.
Exceeded byte count limit is no longer reported as a failure. Instead, bytes are no longer written to a file. Also, I added some guarding against failures that might happen when writing to a file (due to low-end devices and so on).
This change also enables displaying not fully read responses if Chucker is applied as an application-level `Interceptor`. Network-level is not always doable due to compression (this might be further improved in the future but right now I don't want to mess with it).
No.
Some units test are …

Allow Chucker to display partially read application responses

---

sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinApi.kt
sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt
sample/src/main/java/com/chuckerteam/chucker/sample/LargeJson.kt

I wanted to have a sample for a partial download of the content. It is somewhat a follow-up to #384.
I added a new call. It uses Postman instead of httpbin. The reason is that httpbin formats the echoed response in a really strange way as it escapes newline and quotation characters. Also, the cool thing about Postman is that it does not have the `Content-Length` header.
Additional things that I changed is the order of interceptors in the sample. Logging interceptor downloads all of the data before the Chucker can do its thing so this made partial reads impossible on the Chucker level. For this reason, I had to change all responses from `Void` to `Any?` in order to make `Retrofit` automatically read whole bodies of responses and not shortcircuit them.
#384.
No.
Just run the sample and find …

Add sample for partial body download.

---

library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransaction.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransactionTuple.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/room/ChuckerDatabase.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/room/HttpTransactionDao.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/OkHttpUtils.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
library/src/test/java/com/chuckerteam/chucker/ChuckerInterceptorDelegate.kt
library/src/test/java/com/chuckerteam/chucker/TestTransactionFactory.kt
library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/data/entity/HttpTransactionTupleTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/data/entity/TransactionTestUtils.kt
library/src/test/java/com/chuckerteam/chucker/internal/data/repository/HttpTransactionDatabaseRepositoryTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/data/room/HttpTransactionDaoTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/OkHttpUtilsTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/TeeSourceTest.kt

| --- | --- |
| ![Screenshot_20200719-064434](https://user-images.githubusercontent.com/30936061/87867490-878da480-c98d-11ea-808c-8ba16b2b4c07.jpg) | ![Screenshot_20200719-064034](https://user-images.githubusercontent.com/30936061/87867492-89576800-c98d-11ea-8087-fb4c399d4f8b.jpg) |
There is an open issue - #209. Also, recently the community asked for it.
Two main changes. I redesigned a little bit DB entities to reflect that they have payload size and not content length. This required a destructive migration. Since this is changed, the field is set after the response read is done by `ChuckerInterceptor` and it does not rely on the `Content-Length` header.
No.
Run the sample app. Responses without the `Content-Length` headers should display now payload size correctly. …

Do not rely on "Content-Length" for payload size.

---

library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt
library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/TeeSourceTest.kt

There is an open issue - #394.
`TeeSource` guards against failures to use files. When `FileNotFoundException` occurs when opening a stream it is reported back to the caller and no payload side streaming happens. Also, any IO failures during interception are now logged.
No.
Not really sure how to reproduce this manually without a convoluted setup. Maybe @CodeBreak524 can confirm that their issue is fixed with a dependency from my branch on JitPack (`com.github.MiSikora.chucker:library:side-channel-file-failure-SNAPSHOT`). I don't really feel that it is necessary as the description in #394 is quite clear and it is now covered with tests.
Closes #394.
To be honest I wonder now about the necessity to write to a file instead of to the memory. Responses need to be loaded to a memory at some …

Do not fail requests when side channel file cannot be used

---

.github/workflows/pre-merge.yaml

Keeping our Kotlin variant up to date. Version 1.4.0-rc was released yesterday:
https://blog.jetbrains.com/kotlin/2020/07/kotlin-1-4-rc-released/
None
Let's wait for CI tests

Kotlin variant in pre-merge to 1.4.0-rc

---

library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
library/src/main/res/values/strings.xml

While playing with the new [Activity Results API](https://developer.android.com/training/basics/intents/result) I found out that code for saving body to a file is quite verbose with redundant null check. 
Particularly there is a check if transaction is null in a place where it makes no sense to check, since in `onActivityResult()` we already have another check for transaction being null before trying to write its body into a file. 
Additionally, we might want to show toast about saving failure in case `uri` or `transaction` are null in `onActivityResult()`.
- Removed `null` check done via `?.let { }` in file creation function.
- Added missing toast for possible cases of failure during file saving.
- Renamed function `viewBodyExternally()` to `createFileToSaveBody()` to match its …

Minor improvement for transaction saving

---

sample/src/debug/AndroidManifest.xml
sample/src/debug/res/xml/network_security_config.xml

This allows tools like Charles Proxy to intercept/view HTTPS traffic.
I'm working on #401 and wanted to compare my progress to what Charles Proxy can see.
This only change the sample, not the library. If you'd like to test the sample, you can use a tool like Charles Proxy. See https://www.charlesproxy.com/documentation/proxying/ssl-proxying/

Allow user specified certificates in the debug variant of the sample app.

---

build.gradle
pre-commit

This PR implements enhancement #248 to run code checks before commiting the code. Except adding the hook itself I have also added a task to install hook which runs whenever clean task is fired. It means that with such hack every contributor will have hook installed automatically.
- Added `pre-commit` script file
- Added task to install this script file
- Set `clean` task to depend on install task.
Nothing
Run `Clean` or `Rebuild` task and see that `installGitHook` task is executed as well.
After that hook should run on every commit attempt.
We might consider integrating formatting task into the hook as well after adding #249

Add pre-commit hook and task to automatically install it

---

library/src/main/AndroidManifest.xml
library/src/main/java/com/chuckerteam/chucker/internal/support/ChuckerFileProvider.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionListFragment.kt
library/src/main/res/values/strings.xml

This prevents conflicts with other apps that already use the generic androidx.core.content.FileProvider as a name.
This also allows multiple apps with chucker to be installed on a device at one time.
Fixes #409

Fix FileProvider issues.

---

README.md

This is related to #248, I'm adding a Building section to the README to clarify how to setup the local environment for developing the library.
- Added the `Building` with a mention on the ktlint pre-commit hook
- Added the `gradlew build` suggested command in order to run all the tests locally
- Disabled `GradleDependency` lint check as `gradlew build` is failing on master due to obsolete OkHTTP dependency (that's intentional).

Add a Building section to the README

---

library-no-op/build.gradle
library/build.gradle

Fixes #415
These are the only 2 dependencies that have their types exposed by Chucker public types. This ensures that downstream apps that use these APIs will compile.

Make some dependencies api in library build.gradle

---

.github/workflows/pre-merge.yaml
build.gradle

Update Chucker to use Kotlin 1.4.0. It seems that after this update we don't need different Kotlin versions in our workflow anymore.
- Update Kotlin to 1.4.0
- Remove environment variable for different Kotlin versions from Github Actions workflow.
Unblocks #363 
Nothing expected.
Update coroutines dependency to 1.3.9, which already switched to Kotlin 1.4.0

Update Kotlin to 1.4.0

---

build.gradle

Since Chucker already uses Kotlin 1.4.0 we can safely update Coroutines to 1.3.9 as well.
Doing this update manually, since Dependabot picks wrong dependency (like in #426)
- Update Coroutines to 1.3.9.
Nothing

Update Coroutines to 1.3.9

---

README.md
library-no-op/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/DepletingSource.kt
library/src/test/java/com/chuckerteam/chucker/ChuckerInterceptorDelegate.kt
library/src/test/java/com/chuckerteam/chucker/TestUtils.kt
library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/DepletingSourceTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/ReportingSinkTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/TeeSourceTest.kt

There is an issue - #432.
I added `alwaysReadResponseBody` flag to `ChuckerInterceptor` that lets users decide if they want to consume the whole body from responses. It is an opt-in feature because it can drastically change the behavior of an application between QA and production builds.
Sources are depleted with a new `DepeletingSource` class that is added conditionally based on the flag.
I also did some housekeeping on tests.
* The temporary directory is now a property of `ChuckerInterceptorTest` instead of an input argument of test functions.
* Okio's segment size is now a test constant.
No.
There are unit tests to cover this functionality. To tests this manually you can use the sample app, turn on the flag, and see that the response body from Postman call is fully available.
Closes …

Add a flag to always read response body fully

---

library/src/main/java/com/chuckerteam/chucker/internal/support/ChuckerFileProvider.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/ProtocolResources.kt

Found out that in docs generated by Dokka we have more than `api` package available (see the attached screenshot). These packages inside `internal` package shouldn't be visible to users, as well as classes in it. And such classes shouldn't be in docs as well.
- Updated visibility modifier for 2 classes.
Run `dokkaHtml` command and see that generated doc has only `api` package.
Documentation rework is on me, so I will improve documentation when I get back to these tasks soon.

Fix classes visibility

---

library/src/main/java/com/chuckerteam/chucker/api/Chucker.kt
library/src/main/java/com/chuckerteam/chucker/api/RetentionManager.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/Logger.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/Sharable.kt

When going through #451, I noticed we have some orphan `println` that we should avoid. I'm cleaning up the logging infra we have for Chucker a bit.
Introduced a small `Logger` object that will serve for future logging.
n/a

Cleanup logging in the library

---

build.gradle

Decided to update code analyzers, since while working on search feature I was constantly rejected from doing a commit by our pre-commit hook due to this issue with fun interfaces: https://github.com/detekt/detekt/issues/3050
Since I was updating Detekt, decided to update Ktlint as well, along with its plugin.
- Updated Detekt to 1.14.0
- Updated Ktlint to 0.39.0
- Updated Ktlint plugin to 9.4.0
Rebese my branch with search function to avoid false positives from Detekt.

Update Ktlint and Detekt

---

CHANGELOG.md
README.md
gradle.properties

Changelog and version bumps for 3.3.0 release.
Tried to capture all the changes and fixes, but might have missed some. 
Changelog is formed based on 2 sources:
1). [List of PRs](https://github.com/ChuckerTeam/chucker/pulls?page=1&q=is%3Apr+is%3Aclosed+merged%3A2020-04-04..2020-09-29)
2). [3.3.0 milestone](https://github.com/ChuckerTeam/chucker/milestone/9?closed=1)
In updates for dependencies I decided to not include info about updates for things like KtLint and other quality control or debugging tools, since they are meaningless for the library users.

Release 3.3.0

---

README.md

Found out that we need to update list of people to ping in `Contributing` section.
- Removed inactive maintainer 
- Added new team member
- Ordered team in alphabetical order
Will update gifs next, since our sample app has updated UI since `3.3.0`

Update team members list

---

build.gradle
library/src/main/java/com/chuckerteam/chucker/internal/data/repository/RepositoryProvider.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/room/ChuckerDatabase.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/BaseChuckerActivity.kt

Recently saw a leak reported by LeakCanary and investigated the reason. In some cases Room database initialises with activity context instead of application and it leads to leaks. 
- Replaced `this` with `applicationContext` in `BaseActivity` to provide proper `Context` object.
- Renamed params to avoid confusion on which `Context` is required.
- Updated LeakCanary to 2.5.
Nothing
Just launch sample app and try to play around with the app to see if LeakCanary reports something.
Probably, we could redo the way repositories initialisation happen. But it is not the top priority now.

Fix leaking MainActivity

---

build.gradle
library/src/main/AndroidManifest.xml

Something that, probably, had to be done for `3.3.0` before release as well. 
Updates for targetSDK and compileSDK to 30 or Android 11. After checking the whole list of behavior changes I found out that Chucker has almost nothing to change to be compatible. The only thing was [changes for package visibility](https://medium.com/androiddevelopers/package-visibility-in-android-11-cc857f221cd9). While testing saving transaction into a file on emulator with Android 11 saw that I constantly get error. As it turned out `resolveActivity` always returns `null` if no `<queries>` element specified in app's manifest. So I modified `AndroidManifest` file as well to make app compatible with requirements. 
After this change I tested file saving on devices with SDK 19 as well and found no issues.
- …

Bump target and compile SDK to 30

---

README.md

The branch name `release` is stale as we updated to use `main`. I'm updating in the README
n/a

Update branch name in the README

---

CHANGELOG.md

To ease the changelog support and to let our users know what changed in current snapshot versions this PR adds `Unreleased` section, which should be updated as more features/fixes merged into `develop` branch. 
Also, this PR also has slightly different format and titles to describe changes. I suggest such change to follow https://keepachangelog.com/en/1.0.0/ style as we move forward.
- Added `Unreleased` section to `Changelod.md`
- Changed the style of changes description in `Changelog.md`.

Add Unreleased section to changelog

---

library/build.gradle
library/src/test/java/com/chuckerteam/chucker/TestTransactionFactory.kt
library/src/test/java/com/chuckerteam/chucker/TestUtils.kt
library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/data/entity/HttpTransactionTupleTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/data/repository/HttpTransactionDatabaseRepositoryTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/data/repository/RepositoryProviderTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/data/room/HttpTransactionDaoTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/ChuckerCrashHandlerTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/DepletingSourceTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/FormatUtilsTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/FormattedUrlTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/IOUtilsTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/JsonConverterTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/LiveDataCombineLatestTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/LiveDataDistinctUntilChangedTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/OkHttpUtilsTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/ReportingSinkTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/TeeSourceTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/TransactionCurlCommandSharableTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/TransactionDetailsSharableTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/TransactionListDetailsSharableTest.kt

The explicit API mode compiler flag had a typo in the library module.
I fixed the typo. I also added explicit visibility modifiers to tests. I used `internal` because it's less work than to mark everything as `public`.
#363
No.

Fix compiler flag for explicit API mode

---

CHANGELOG.md
library/build.gradle
sample/build.gradle
sample/src/main/java/com/chuckerteam/chucker/sample/MainActivity.kt

There is an open issue #480 . To fix it, I suggest to remove the `kotlin-android-extensions` plugin from the library.
Also, Chucker uses `ViewBinding` for quite a long time already, so we can get rid of this plugin anyway.
- Removed `kotlin-android-extensions` plugin from `library` module.
- Removed `kotlin-android-extensions` plugin from `sample` module.
- Enabled `ViewBinding` in `sample` module.
Nothing
Run sample app and see that everything works fine.
Closes #480

Remove kotlin-android-extensions

---

library/src/main/java/com/chuckerteam/chucker/internal/support/IOUtils.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/IOUtilsTest.kt
sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinApi.kt
sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt
sample/src/main/java/com/chuckerteam/chucker/sample/MainActivity.kt

There is an issue #472 
Issue appears with StrictMode enabled. We couldn't catch the issue earlier, because sample app has no gzip request with body, so code with error wasn't reachable.
- Fixed the issue by adding `use { }` function to GzipSource in `getNativeSource()` function.
- Updated tests to use real `Buffer()`, since Mockk can't properly react to `close()` call.
- Added a fake Gzip request which I fill with some dummy request body and header telling that response is with gzip encoding. It returns 405, but allows to reproduce the issue.
- Added StrictMode to the sample app, because this is not the first time we have issues reported by people with this mode enabled (for example #421)
- (UPD: after review) Renamed existing gzip request to explicitly mention that it returns just gzip …

Fix for not closed GzipSource

---

CHANGELOG.md
README.md
library-no-op/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt

It is a follow up to the discussion in #483. It also addresses #462 and #466.
I added a builder pattern in a `3.x` compatible way. This way users will be informed of changes and have more time to adjust their code. Unfortunately, `ReplaceWith` is not ideal. `imports` do no work properly with default arguments but IMHO it is a minor inconvenience (basically, only `ChuckerCollector` needs to be manually imported). Also, it will create builder with all fields. I've tried to split constructor into different ones with different `ReplaceWith` strategies but it is not possible due to named arguments and source compatibility in Kotlin.
#462
No.
You can check if `ReplaceWith` works correctly.
Prepare `3.4.0` release and `3.x` branch.

Use builder pattern for ChuckerInterceptor in a backwards compatible way

---

.github/workflows/gradle-wrapper-validation.yml
.github/workflows/pre-merge.yaml
README.md
gradle.properties

Updates to move forward
- Updated version name and code for snapshot builds
- Updated readme file to actual versions

Prepare for next release

---

CHANGELOG.md
library-no-op/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/test/java/com/chuckerteam/chucker/ChuckerInterceptorDelegate.kt
sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt

There is an issue - #462.
This implementation uses more robust builder pattern in terms of future development. It should be used with `4.x`. There is one inconvenience when it comes to default values but it is not that big of a deal. I'll describe it more in the comments to the code.
Yes it breaks both API and ABI, but it is for `4.x`.
~~I suggest reviewing commits separately. With 5e7d733 you can check if `ReplaceWith` works correctly.~~
Nothing special to test.
Closes #462
Helps with #466. It does not solve it, but I don't think we can fix it unfortunately. We can only make sure that in the future we don't fall into the same trap. Though suggestion with adding ABI compatibility tool would be a nice addition.
We should consider doing the same with `ChuckerCollector` and …

Remove deprecated constructor and use exposed builder pattern

---

library/src/main/java/com/chuckerteam/chucker/internal/data/model/DialogData.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/ContextExt.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionListFragment.kt

We had a typo in the `DialogData` class.
Updating the property name from `postiveButtonText` to `positiveButtonText`
n/a

Fixed typo on DialogData

---

sample/build.gradle
sample/src/main/res/layout/activity_main_sample.xml
sample/src/main/res/values/dimens.xml

| --- | --- |
| <img src="https://user-images.githubusercontent.com/13467769/100138619-f8425180-2e96-11eb-80a3-b240c175284e.png" width="250" /> | <img src="https://user-images.githubusercontent.com/13467769/100138713-1c059780-2e97-11eb-935d-8e6b7115de55.png" width="250" /> |
| --- | --- |
|<img src="https://user-images.githubusercontent.com/13467769/100138614-f6788e00-2e96-11eb-9185-07ad04c114d1.png" width="400" /> | <img src="https://user-images.githubusercontent.com/13467769/100138749-27f15980-2e97-11eb-8d65-200ab36d2e9d.png" width="400" /> |
Saw that we forgot to remove `Trigger an exception` button when were removing throwables funcitonality. So I removed this button. Since I was editing this layout anyway I decided to improve it to make it more …

Update Sample app layout

---

library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt

We are still using a couple of deprecated methods from OkHTTP 3 that are being reported during the builds.
Changing those methods with the corresponding OkHTTP 4 equivalents

Fix a couple of OkHTTP 4 deprecations

---

.github/workflows/pre-merge.yaml
sample/build.gradle
sample/src/debug/AndroidManifest.xml
sample/src/main/res/values/dimens.xml
sample/src/main/res/values/strings.xml

Lint is currently broken on `develop`. I'm fixing it and I've added a job on GH Actions to run it on pre-merge. If you happen to run `gw check` to run all the verifications, it will fail.
- Disabled `AcceptsUserCertificates` as we intentionally want to allow user CAs
- Fixed error on `android:networkSecurityConfig`
I believe we should update the pre-commit hook to run `gw check`

Fix broken lint and add it to GH Actions

---

.github/workflows/pre-merge.yaml
build.gradle
library-no-op/api/library-no-op.api
library/api/library.api

To prevent problems like #466 in the future, I'm introducing https://github.com/Kotlin/binary-compatibility-validator to Chucker.
This will force any PR that touches the public API, to also include a change to the corresponding `.api` file. To recompute the `.api` file, developers should just call `gw apiDump`.
- Introduced `binary-compatibility-validator` plugin
- Added a new GH Actions job for running `apiCheck` before merging
- Excluded project `sample` and non public packages from the API surface.
Follow-up from #466
None
Please take a look at the `.api` file and let me know if you agree on it.
If the CI is green, we should be good to go.
n/a

Add binary-compatibility-validator to Chucker

---

library-no-op/api/library-no-op.api
library-no-op/build.gradle
library/api/library.api
library/build.gradle
sample/build.gradle

Before
After
Chucker has `BuildConfig` available in the public API as mentioned [here](https://github.com/ChuckerTeam/chucker/pull/509/files#r532265254), but generating this file has no value for customers. 
This PR disables `BuildConfig` generation in both `library` and `library-no-op` modules as well as in the `sample` app module.
- Added `buildFeatures.buildConfig = false` to every module.
Yes, with this change we are breaking Chucker public API. 
Use the library from this branch and try to refer to `BuildConfig` in the app using Chucker.

Disable BuildConfig generation

---

library/build.gradle

Since we are going to add more OkHttp packages, for example, to implement #202 I suggest us to switch to BOM for OkHttp.
I think that we are fine with using BOM only in the `library` module, since in `library-no-op` and in `sample` we use only one package from OkHttp set.
- Switched to BOM for OkHttp dependencies in `build.gradle` file
Nothing breaking expected

Switch to OkHttp BOM in the library module

---

library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransactionTuple.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/TransactionDiffCallback.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/MainActivity.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionAdapter.kt

Something that I mentioned in different chats or issues (for example [here](https://github.com/ChuckerTeam/chucker/issues/286)), but never delivered - updating transactions list nicely with `DiffUtil` via `ListAdapter`
- Switched from regular `RecyclerView.Adapter` to `ListAdapter`
Nothing breaking expected
Run the sample app and check how transactions list updates when some network activity happens and during the search

Use ListAdapter for TransactionsAdapter

---

library/src/main/java/com/chuckerteam/chucker/api/Chucker.kt
library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/main/java/com/chuckerteam/chucker/api/RetentionManager.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/DepletingSource.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/FileFactory.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/Logger.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/Sharable.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
library/src/test/java/com/chuckerteam/chucker/NoLoggerRule.kt
library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/DepletingSourceTest.kt

Some parts of the code used `printStackTrace()` to log failures. I wanted to centralise logging point that can be used in Chucker. This also gives an opportunity to let users set an external logger in the future.
I changed `Logger` to an interface and made an instance of it available in `Chucker` object. Companion object of `Logger` delegates then to this property.
I also added a test extension that sets no-op logger. It is needed as we can't have a centralised logger that is not static due to logging in Android components as well.
One more thing – I removed "Chucker" from log messages. It is present in the tag anyway.
#452
No.
Nothing special to check. Rely on unit tests.
N/A

Centralise all logging in Chucker

---

gradle/wrapper/gradle-wrapper.properties

- Gradle wrapper version is 6.8.1 now

Update Gradle wrapper to 6.8.1

---

library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt

There is a bug while processing requests.
I set a correct property on a transaction. Previously it used response, now it uses request.
#527
No.
I added a test that covers the bug.

Fix setting request body plain text in transaction

---

library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt

`ChuckerInterceptor` response tests had incorrect naming.
Changed test names to convey better what they check.
#527
No.

Fix HTTP response test names

---

library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/IOUtils.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/OkHttpUtils.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/OkioUtils.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/IOUtilsTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/OkHttpUtilsTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/OkioUtilsTest.kt

Just some cleanup of IO utils that was done along the way of #527. Moving methods out of `IOUtils` class to some extensions functions etc.
As mentioned. It is mostly moving internal parts that are about IO and HTTP to separate classes.
#527
No.
Nothing changed in that regard. Tests were adjusted accordingly.

Refactor IO utils

---

.github/workflows/pre-merge.yaml
.github/workflows/publish-snapshot.yaml

Github Actions has no feature to cancel previous workflow execution if some new push even happens triggering the same workflow again. In Chucker case it happens when somebody merges multiple PRs to `develop` one after another firing multiple runs of checks and snapshot publishing. It is not a big deal, but not efficient.
With suggested action: https://github.com/styfle/cancel-workflow-action we can improve efficiency by cancelling previous running builds.
- Modified `pre-merge` and `publish-snapshot` actions to automatically cancel workflows if new trigger event happened.
- Added a few empty lines to separate steps in workflows.
It might be that pushing code to different PRs quite fast will cancel `pre-merge` running for some other build, but not sure if we have such cases.
- Open some PR …

Auto cancel workflow when new push happens

---

CHANGELOG.md

A bug fix wasn't mentioned in the changelog.
I updated the changelog.
#538 
No.

Add missing fix to changelog

---

.github/PULL_REQUEST_TEMPLATE

Looks like we need to add a reminder for everyone contributing to Chucker about keeping changelog up to date.
The PR addresses a similar suggestion from #545.
- Added a comment into a PR template reminding to update changelogs.

Update PR template with a comment about release notes 

---

build.gradle
library/src/main/res/layout/chucker_fragment_transaction_payload.xml

Material 1.3.0 has some [new components for progress indicators ](https://github.com/material-components/material-components-android/blob/master/docs/components/ProgressIndicator.md). This PR updates Material to 1.3.0 and switches loading indicator used on transaction payload fragment to such new component.
- Updated Material to 1.3.0
- Switched to `CircularProgressIndicator` component
Nothing

Update Material to 1.3.0, switch to new CircularProgressIndicator

---

library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/RequestProcessor.kt

Due to mishaps in #542 I'm putting this for review. If there are any comments I'll fix them in this PR and then create a new one with fixes only that target develop. Below is the copy of description from #542.
`ChuckerInterceptor` was doing too much and it would be hard to integrate #523 in a sane manner.
I refactored code responsible for requests processing.
* Added `LimitingSource` that replaces method on `IOUtils` that read limited amount of content. Due to that `chucker_body_unexpected_eof` message is removed as it is now impossible to read too much from in-memory buffers while processing the response.
* Added `RequestProcessor` that moves away request logic from the interceptor.
* `HttpTransaction` has `isRequestBodyPlainText` is now set to false by default and changed to true only …

Request processing refactor

---

CHANGELOG.md
library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/OkHttpUtils.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/RequestProcessor.kt
library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt

Request headers were not redacted if there were communication failures.
Request headers are redacted also in a request processing pipeline.
#527
No.
I added unit tests.
This can wait with merging after #543 is resolved.

Redact request headers in case of HTTP failures

---

CHANGELOG.md
library/src/main/java/com/chuckerteam/chucker/internal/support/RequestProcessor.kt
library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinApi.kt
sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt

Processing one shot request bodies is a bug as it means that after we process them, they cannot reach the server. Processing duplex request bodies is problematic as the bytes can be intertwined and out of order for us to process them.
One thing that is not that obvious is the message that users see in the Chucker UI as the body processing was omitted for a different reason.
We could add new fields to the database model and show appropriate information based on that or we can change the single message that we have. I'm open to both propositions.
I added two conditions that check if a request body should be processed. If they are positive the event is logged and request processing is stopped. I also added a sample that utilises a one shot request body.
#527
No.
Tests were added. …

Do not process one shot and duplex request bodies

---

library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransaction.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/ResponseProcessor.kt
library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt

This is the final PR that is a result of splitting #527.
Similarly to the `RequestProcessor` class I added the `ResponseProcessor` class that does the analogous stuff. I changed one thing, where plain text body is set to be `plainText  = true` only when there is some content. I don't think it made sense to set it to `true` when there was no body.
#527
No.
Rely on CI. Manually you can simply check the sample app.
N/A

Response processing refactor

---

library/build.gradle

Lint started to fail builds because some dependencies have newer versions. It is quite annoying to see.
Check #555, #556, for example.
I decided to disable such rule, because it shouldn't be a blocker
- Disabled lint rule for checking dependencies version.
Nothing expected 
Lint check shouldn't fail on CI for this PR
Update other branches suffering from this lint check.

Disable lint check for dependency versions

---

build.gradle
library/build.gradle
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt

Since Activity and Fragment with the new Activity Result API to replace things like `startActivityForResult()` are stable I have blown off dust from my branch where I tried to apply this new API in Chucker and updated dependencies to use stable library versions.
- Updated Activity to 1.2.0
- Updated Fragment to 1.3.0
- Replaced `startActivityForResult()` used to save file with payload with new Activity Result API
Nothing breaking expected and I wasn't able to find any broken things while testing, but [Fragment 1.3.0](https://developer.android.com/jetpack/androidx/releases/fragment#1.3.0) has quite a lot of changes, like new state manager.
Nothing changed from UX point of view, so the save operation works as before.
Deal with more deprecations in Chucker codebase.

Switch to Activity Result API

---

.github/PULL_REQUEST_TEMPLATE

PR template has an unclosed comment in the changes section.

Add missing comment closing to PR template

---

library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt

Before:
After: 
Looks like #555 introduced a bug with payload UI. All empty bodies started to show `encoded or binary body omitted` string while they should be empty. Except fixing this I added a string resources to show in empty bodies transactions, like we do when trying to share transactions.
- Changed conditions in payload processing in `TransactionPayloadFragment`.
- Added string resource to clear indicate that body is empty.
Nothing
Run sample app and check some transactions with emtpy requests/responses 
I thing I found one more bug introduced by #555, but want to check how Chucker behaved in `3.4.0` to understand if it is really something new.

Fix UI for emtpy body in request/response

---

.github/dependabot.yml

Dependabot lacked info on who should be in reviewers for Github Actions updates PRs.
So in #565 there were no reviewers assigned.
- Added the same reviewers to config for Github Actions PRs
Nothing
Wait for another Dependabot PR for Github Actions

Add reviewers for Github Actions updates PRs

---

sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt
sample/src/main/java/com/chuckerteam/chucker/sample/InterceptorType.kt
sample/src/main/java/com/chuckerteam/chucker/sample/InterceptorTypeSelector.kt
sample/src/main/java/com/chuckerteam/chucker/sample/MainActivity.kt
sample/src/main/res/layout-land/activity_main_sample.xml
sample/src/main/res/layout/activity_main_sample.xml
sample/src/main/res/values/strings.xml

There is an open issue – #389.
I wanted to split `HttpBinClient` into smaller pieces but first I wanted to add the ability to test `ChuckerInterceptor` both as an application type and as a network type interceptor without changing it in the code.
I added a radio group to the sample UI that allows to choose how `ChuckerInterceptor` will be applied. Based on a selected radio button the interceptor is active in one or the other pipeline.
Behaviour is slightly different than the one described in #389. Interceptor type can be changed on the fly while requests are being performed. Making it toggleable only during idle periods would be too complex as it would require either two HTTP clients or some syncing and queueing mechanisma.
No.
Play with the sample and toggle radio buttons.
Closes #389.

Allow to choose interception type in the sample

---

CHANGELOG.md
library/src/main/java/com/chuckerteam/chucker/api/ChuckerCollector.kt
library/src/main/java/com/chuckerteam/chucker/api/RetentionManager.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/repository/HttpTransactionDatabaseRepository.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/repository/HttpTransactionRepository.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/room/HttpTransactionDao.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/ClearDatabaseService.kt

There is an issue – #487. While at first I was reluctant to fix it, because I didn't want to do some strange executor delegation inside closing to avoid talking to the database on the main thread, I actually checked the code today and all of the work can be delegated to Room.
I made `transactionUpdate()` function suspending. This delegates internally in Room to Architecture Components executor. Additionally I fixed coroutine scopes. Previously we created a scope per request in collector or retention manager. Now they have their own scopes.
No.
Change `ReadBytesCallback` in the sample to something like this.
```kotlin
class ReadBytesCallback(
private val byteCount: Long? = null,
) : Callback {
override fun onFailure(call: Call, e: IOException) {
e.printStackTrace()
}
override fun …
```

Make transaction updates suspending

---

library/src/main/java/com/chuckerteam/chucker/internal/support/NotificationHelper.kt

Android 31 [requires](https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability) to specify mutability of pending intents.
I added mutability flag to our pending intents.
No.
Not sure, run on Android 31?
Either cherry–pick it to `3.x` or plan release of `4.x` soonish.

Add immutable flag to pending intents

---

build.gradle

Future-proofing Chucker by limiting usage of Jcenter. Most dependencies now resolved through `mavenCentral` instead. 
~~However, there was one issue with `org.jetbrains.trove4j:trove4j`, which is used by `android-lint`, so I had to add `gradlePluginPortal()` to `allprojects` section or the build process would fail for me. Not sure how it helps, considering that I couldn't find `trove4j` on Gradle portal.~~
Jcenter left only for dependencies, which can't be resolved via `mavenCentral`.
- Removed `jcenter` from repositories in `buildscript`.
- Added `mavenCentral` to `allprojects` section.
- (UPD: 08.04.2021) Limited usage of Jcenter only to required dependencies in `allprojects` section: `trove4j` and `kotlinx-html-jvm`

Limit Jcenter usage

---

library/src/main/AndroidManifest.xml
library/src/main/java/com/chuckerteam/chucker/internal/support/ClearDatabaseJobIntentServiceReceiver.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/ClearDatabaseService.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/NotificationHelper.kt

Chucker used `IntentService` for notification action to clear transactions database, which is currently deprecated.
To address this deprecation this PR replaces `IntentService` with `JobIntentService`. 
Since `JobIntentService` requires call to `enqueueWork()` function I had to use `Broadcast` and declare `BroadcastReceiver` which would call `enqueueWork()` when required.
Additionally, I had to add `WAKE_LOCK` permission for pre-Oreo devices or Chucker would crash on devices with API < 26.
- Switched from `IntentService` to `JobIntentService`
- Declared a `BroadcastReceiver` to receive `Clear` action events.
- Added `WAKE_LOCK` permission for pre-Oreo devices.
Nothing breaking expected
No special requirements. Just try `Clear` action from some Chucker notification and everything should …

Replace IntentService with JobIntentService

---

gradle/wrapper/gradle-wrapper.properties

There has been two point releases for Gradle 7. Let's bump to the latest stable.
https://docs.gradle.org/7.0.2/release-notes.html

Gradle to 7.0.2

---

library-no-op/build.gradle
sample/build.gradle

In some PRs lint on CI fails due to new version of some dependency being available. It is not something that important to fail the build. Previously we added an exception for such cases, but only in `library` module. This PR adds the same exception rule to `no-op` and `sample` modules.
Additionally added and exception about RTL to `no-op` module, since it looks like it should be there as well.
- Updated lint rule in `no-op` and `sample` modules.

Update lint options

---

CHANGELOG.md
README.md

Updates to CHANGELOG and README files for next `3.5.0` release
This PR should be merged after #637 is merged and released to not misinform users
Not sure if we need this PR in `3.x` branch as well, since `develop` is a source of truth for users.

Update readme and change list

---

.github/workflows/close-and-release-repository.yaml
.github/workflows/publish-release.yaml
.github/workflows/publish-snapshot.yaml
build.gradle

I've setup a manual GH Actions workflow to trigger the closing/publishing of the sonatype plugin.
I've used the `io.codearte.nexus-staging` to achieve this. I wanted to use https://github.com/gradle-nexus/publish-plugin/ but just closing the repo was not supported due to https://github.com/gradle-nexus/publish-plugin/issues/19
I've also added the `--no-parallel` flag on the publishing tasks as I noticed that two Staging Repositories gets created whenver a new tag is published. This should mitigate the issue.
I've tested the plugin locally when releasing `3.5.0`. We can try the GH workflow end to end on the next release.

Setup automatic repo closure

---

library/src/main/java/com/chuckerteam/chucker/internal/support/NotificationHelper.kt

Originally reported here https://github.com/ChuckerTeam/chucker/issues/634#issuecomment-880196269
When we backported this PR #593, the `PendingIntent` for the error screen slipped through. Therefore users
Just adding the `FLAG_IMMUTABLE` to the only `PendingIntent` that was missing it.
#593 and #637
I haven't tested this, it's a best guess fix.
We should potentially release `3.5.1` with this fix included. Wdyt @vbuberen @MiSikora

Correctly set `FLAG_IMMUTABLE` for error screen `PendingIntent`

---

sample/src/debug/AndroidManifest.xml
sample/src/main/AndroidManifest.xml

Another change required before app can target Android S (12) is requirement to set `exported` for all components in app's manifest: https://developer.android.com/about/versions/12/behavior-changes-12#exported
We didn't have it, so I couldn't build sample to test with `targetSDK` changed to 31. To fix it and prepare for future `targetSDK` change I did this small update.
- Added `exported=true` to sample's `MainActivity`, so it could be launched on devices with Android 12 when `targetSDK` is set to 31.
Pick it into `3.x` as well before creating a new patch release.

Explicitly set exported property for sample

---

CHANGELOG.md
README.md

Preparations for patch 3.5.1 release
- Updated release notes and readme
Blocked by #655 as we need to release 3.5.1 first

Release 3.5.1 changelogs

---

CHANGELOG.md

Changelogs changes on 3.x branch for consistency
- Updated changelogs to include 3.5.0 and 3.5.1 releases

Old release notes for 3.x

---

.github/workflows/publish-release.yaml
.github/workflows/publish-snapshot.yaml

I'm adding the `--no-parallel` flag to publishing on the `3.x` branch. The flag was added only to the `develop` branch so far, I'm replicating it to `3.x` as well.
This is basically re-applying part of #641 on the `3.x` branch.
n/a
There is no real way to test this. Let's see if we need to release another version from `3.x` if we end up in the same problem as #661

Add ` --no-parallel` to 3.x branch

---

README.md

To have less issues, like #608, decided to add mention of headers which might be missed when Chucker is applied as application interceptor
- Updated README

Add examples of possible missing headers in FAQ

---

gradle/wrapper/gradle-wrapper.properties

Just bumping Gradle to 7.2 as it was older (7.3 is also near). This doesn't get bumped automatically by dependabot.
CI
n/a

Gradle to 7.2

---

library/src/main/java/com/chuckerteam/chucker/internal/support/TransactionListDetailsSharable.kt
library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorDecodingTest.kt
library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/ReportingSinkTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/TeeSourceTest.kt

Small refactoring while investigating #714.
Fixed some typos and removed redundant use of `apply` on `okio.Buffer`.

Drop redundant `apply` on buffers

---

CHANGELOG.md
library/src/main/res/layout/chucker_transaction_item_body_line.xml

All TextView(s) must be LTR because in RTL language the payload will be affected and we have some problems
When our app is RTL mode we have some problems with payload texts.
I added force LTR text direction in payload items.

Fix RTL issue in payload

---

README.md

https://developer.android.com/guide/topics/ui/notifiers/notifications
"A notification is a message that Android displays outside your app's UI"
push notification requires some network traffic, which I believe is not the case

it's not push notification, it's a notification

---

README.md

The Chucker notification is incorrectly referred to as a push notification.
Documentation change only.
Just correcting some terminology.
Just removed one word from the Readme
None.
No breaking changes.
Read the Readme.
No next steps.

It's not a push notification, it's a notification

---

library/src/main/kotlin/com/chuckerteam/chucker/internal/support/Sharable.kt
library/src/main/kotlin/com/chuckerteam/chucker/internal/ui/BaseChuckerActivity.kt
library/src/main/kotlin/com/chuckerteam/chucker/internal/ui/MainActivity.kt
library/src/main/kotlin/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt

Saw a memory leak pop up in LeakCanary.  May be related to Toasts using Activity Context.
Android Docs suggest using ApplicationContext for Toasts: https://developer.android.com/guide/topics/ui/notifiers/toasts
Issue found in Leak Canary.
Found all instances of `.makeText(` and ensured it's being passed `applicationContext`.
No.
Use these features of the library and ensure that the toasts are still properly shown.
This is it, just merging.
----
Leak Trace from Leak Canary:
```
┬───
│ GC Root: Thread object
│
├─ ...RealLocalThumbManager$Thumbnailer instance
│    Leaking: NO (...Application↓ is not leaking)
│    Thread name: 'LocalThumbManager$Thumbnailer'
│    mContext instance of ...Application
│    ↓ RealLocalThumbManager$Thumbnailer.mContext
├─ ...Application instance
│    Leaking: NO …
```

Memory Leak with Toasts: Use applicationContext instead of Activity

---

build.gradle
gradle/gradle-mvn-push.gradle
library-no-op/build.gradle
library/build.gradle

Currently, the build outputs a warning about the AGP publishing DSL and requires to move to the new way of publishing Android Libraries. I'm addressing it here.
- Removed the explicit Dokka configuration, AGP is encapsulating it.
- Defined a single variant pubblication for both `library` and `library-no-op` picking their release variant
Verified locally with `gw publishToMavenLocal`. A Snapshot will also be published.

Switch to publishing with the AGP publishing DSL

---

build.gradle
detekt-config.yml
library-no-op/src/main/kotlin/com/chuckerteam/chucker/api/Chucker.kt
library-no-op/src/main/kotlin/com/chuckerteam/chucker/api/ChuckerCollector.kt
library-no-op/src/main/kotlin/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library-no-op/src/main/kotlin/com/chuckerteam/chucker/api/RetentionManager.kt
library/src/test/kotlin/com/chuckerteam/chucker/internal/data/har/ContentTest.kt
library/src/test/kotlin/com/chuckerteam/chucker/internal/data/har/EntryTest.kt

Just noticed we have a variety of build warnings I'd like to resolve as they're noisy and not really valuable.
- Remove jcenter()
- Set maxIssues for detekt to 0, and suppressed `LongMethod` on tests
- Suppressed UNUSED_PARAMETER on `library-no-op`
- Fixed several type inference issues in our tests
Essentially wait for a green CI.

Fix various build warnings

---

build.gradle
library/src/main/kotlin/com/chuckerteam/chucker/internal/data/room/HttpTransactionDao.kt

I had to manually bump Kotlin to 1.7.10 as the compilation was failing on our Room classes.
Closes #846 
Closes #850 
Tests are attached
N/A

Bump Kotlin to 1.7.10

---

library/src/main/kotlin/com/chuckerteam/chucker/internal/data/repository/HttpTransactionDatabaseRepository.kt
library/src/main/kotlin/com/chuckerteam/chucker/internal/data/room/HttpTransactionDao.kt
library/src/test/kotlin/com/chuckerteam/chucker/internal/data/repository/HttpTransactionDatabaseRepositoryTest.kt
library/src/test/kotlin/com/chuckerteam/chucker/internal/data/room/HttpTransactionDaoTest.kt

[issue#847](https://github.com/ChuckerTeam/chucker/issues/847)
1. Added a clause to the `getFilteredTuples` in the `HttpTransactionDao.kt` which enables filtering on the basis of `GraphQLOperationName`.  
In order to avoid any breaking changes the `pathQuery` argument is utilized to filter on the basis of `graphQLOperationName`.
I'm wondering if the argument name could be renamed to `filterQuery`? 
2. Tests in `HttpTransactionDatabaseRepositoryTest.kt` & `HttpTransactionDaoTest.kt` have been updated
🚫 
🚫 
1. Launch Chucker Sample.
2. Click on `DO HTTP ACTIVITY` & `DO GRAPHQL ACTIVITY`
3. Click `LAUNCH CHUCKER ACTIVITY`
4. Click on the Search icon. And type "sea"
Chucker should filter the transactions and display a GraphQL transaction with the operation name as `SearchCharacters`

🔍  Filter transactions based on `graphqlOperationName`

---

sample/src/main/res/layout-land/activity_main_sample.xml
sample/src/main/res/layout/activity_main_sample.xml
sample/src/main/res/values/strings.xml

I've just noticed that the sample app looks really odd on my mdpi emulator. I'm fixing the layout here.
| -- | -- |
| ![Screenshot_1677327199](https://user-images.githubusercontent.com/3001957/221356506-16eb8a81-d742-44d8-b790-e015f1fa5123.png) | ![Screenshot_1677327535](https://user-images.githubusercontent.com/3001957/221356513-e5704581-038c-49b1-9521-1374bd8ce608.png) |
I've also removed the `title` as we already have the app bar occupying space.
n/a
none
See the screenshots
n/a

Fix sample app on smaller devices

---

sample/build.gradle

This fixes the deprecation we have on the Apollo Gradle Plugin:
```
> Configure project :sample
Apollo: using the default service is deprecated and will be removed in a future version. Please define your service explicitly:
apollo {
service("service") {
packageName.set("com.chuckerteam.chucker.sample")
}
}
```
See above
n/a
n/a
If the app builds, we're good to go 👍

Fix apollo deprecation

---

sample/src/main/kotlin/com/chuckerteam/chucker/sample/MainActivity.kt

Our Sample app is crashing due to `LeakedClosableViolation`. I believe there is an underlying leak in the framework somewhere. I've reported this to Google here:
https://issuetracker.google.com/issues/270704908
In the meanwhile, I'd move the `LeakedClosableViolation` to just log and don't crash the app till we understand what's causing the change.
Try the sample app and verify it doesn't crash with:
```
StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks. Callsite: close
at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1992)
at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:347)
at …
```

Do not kill the app on Leaked Closeable

---

library/src/main/kotlin/com/chuckerteam/chucker/api/ChuckerCollector.kt

The sample app is insta-crashing when doing http activity.
That happens because we're calling `RepositoryProvider.transaction()....` on the UI thread.
| -- | -- |
| ![before](https://user-images.githubusercontent.com/3001957/221365546-b79f4533-ad7f-47d6-8166-0debf02f9cbf.mp4) | ![after](https://user-images.githubusercontent.com/3001957/221365560-c9e73d9c-14d4-426e-b7bc-36211d601489.mp4) |
nope
See the atteched video
n/a

Fix `DiskReadViolation` on ChuckerCollector

---

library-no-op/api/library-no-op.api
library-no-op/src/main/kotlin/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/api/library.api
library/src/main/kotlin/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/test/kotlin/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
library/src/test/kotlin/com/chuckerteam/chucker/util/ChuckerInterceptorDelegate.kt
sample/src/main/kotlin/com/chuckerteam/chucker/sample/HttpBinHttpTask.kt
sample/src/main/kotlin/com/chuckerteam/chucker/sample/OkHttpUtils.kt

Fixes #266 
I added a public API, `skipPaths(paths:List<String>)`, to the `ChuckerInterceptor.Builer`. 
The ChuckerInterceptor decides to process the transaction based on the outcome of the lambda in `skipEndpoints`.
Adding `skipPaths(..)` to the `ChuckerInterceptor.Build` will be a breaking change. 
- Added tests to `ChuckerInterceptorTest`
- I've also added another endpoint `/anything` to the [HttpBinHttpTask.kt](sample/src/main/kotlin/com/chuckerteam/chucker/sample/HttpBinHttpTask.kt) and added `/anything` to the skip paths list in the sample app.

Add `skipPaths` to selectively skip requests from Chucker

---

library-no-op/build.gradle
library/build.gradle
sample/build.gradle

When we bumped to AGP 8, I also updated JDK version to 17.
The problem is that now the .jar are created with source/target version of Java 17, so they're unusable on older version of Java.
This fixes it.
Fixes #1019
Fixes #1010
Nop
The CI should be able to build
N/A

Use JDK Toolchain for 11

---

CHANGELOG.md
library/src/main/kotlin/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
library/src/main/res/values/strings.xml

Fixes #1030
I'm preventing the file selector to start entirely if the body is empty, and returning a more informative error message to user.
n/a
See gif.
None

Improved error message when trying to save empty bodies

---

.github/workflows/publish-snapshot.yaml
README.md

N/A
The `develop` branch is not exist any more. But the CI is still configured to use `develop` branch to trigger SNAPSHOT build.
So the Sonatype maven repository doesn't provide latest SNAPSHOT build.
Update the `Publish Snapshot` job to use `main` branch instead of `develop` branch
https://github.com/ChuckerTeam/chucker/issues/1044

Fix main branch snapshot CI setting

---

CHANGELOG.md
README.md

I've noticed a couple of typos in the README and in the CHANGELOG after we released 4.0.0.
Fixing them here.

Fix post-release typos

---

library/src/main/kotlin/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt

Issue - Search for something on the response page, the search results are visible along with the nav bar, but when we append something to the query, that leads to zero search results, highlighting is reset, but the nav bar with old search results is still visible.
#988 
- Search for a word available on the response page, and append something making it a query that won't have any results. the nav bar and the highlighted results should be reset.

Bug fix - Scroll to Search Navigation Bar Visibility Fix

---

README.md

This is only a documentation change.
Hi! The permission name used in the docs isn't correct: `POST_NOTIFICATION`, it should be `POST_NOTIFICATIONS` (plural) - although for completeness' sake, I'm proposing that this be `android.permission.POST_NOTIFICATIONS`.
Interestingly the [official docs have the same issue in at least one place](https://source.android.com/docs/core/display/notification-perm):
Although clicking through that link shows the correct naming: https://developer.android.com/develop/ui/views/notifications/notification-permission:

Correct permission name to `android.permission.POST_NOTIFICATIONS` in docs

---

build.gradle

Bumping compile/target SDK to the latest stable.
Also
Closes #1108
Closes #1109
as those two PRs were blocked by this
n/a
n/a
I've tested this locally and the sample app renders correctly.

compile/target SDK to 34

---

CHANGELOG.md
library/src/main/kotlin/com/chuckerteam/chucker/internal/data/entity/HttpTransaction.kt

Fixes "TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved." errors.
N/A
One may use Chucker with optimized builds.
Change how type tokens for lists are created so it works also in optimized/shrinked builds.
Just a different GSON API is now used, no changes in effects.
N/A
Nothing
Use chucker (standard, not no-op) with a release build type or enable minification in debug build type.
N/A

Use parametrized type tokens for GSON converters

---

CHANGELOG.md
library/proguard-rules.pro

Preserve `TypeToken` generic signature, to fix issue with ProGuard.
I only added `TypeToken` rule from [Gson example proguard file](https://github.com/google/gson/blob/main/examples/android-proguard-example/proguard.cfg). This fixes the the problem from related issue. I didn't notice any need for adding additional rules.
Fixes #1183
Added ProGuard consumer rules, to avoid Gson TypeToken releated crash.
Test in release mode with ProGuard enabled.

fix: Gson ProGuard issue

---

library/src/main/res/layout/chucker_activity_main.xml

Layout updated.
A layout xml file
No

fix : display the toolbar subtitle properly [#1217]

---

CHANGELOG.md
library/build.gradle
library/src/main/kotlin/com/chuckerteam/chucker/internal/support/FileSaver.kt
library/src/main/kotlin/com/chuckerteam/chucker/internal/ui/MainActivity.kt
library/src/main/kotlin/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
library/src/main/res/menu/chucker_transaction.xml
library/src/main/res/menu/chucker_transactions_list.xml
library/src/main/res/values/strings.xml
library/src/test/kotlin/com/chuckerteam/chucker/internal/support/FileSaverTest.kt

I usually test my apps on an emulator that isn't connected to Google services. This means I can't directly share transactions with others, as I don't have suitable apps for that purpose. Instead, it's much easier for me to save transactions locally and then share the file from my computer using Device Explorer.
Chucker only supported sharing transaction details as text or HAR but lacked direct file saving capabilities (you could save only a one request/response body).
This PR adds a feature to save all transactions on the local storage. New save buttons are located within share menu separated from share buttons group by divider.
- Introduced "Save as Text" and "Save as HAR" buttons to the share menu, grouped together and visually separated from existing share options.
- Implemented …

Add save all transactions functionality

---

CHANGELOG.md
detekt-config.yml
library-no-op/api/library-no-op.api
library-no-op/src/main/kotlin/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/api/library.api
library/src/main/kotlin/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/test/kotlin/com/chuckerteam/chucker/api/ChuckerInterceptorSkipRequestTest.kt
library/src/test/kotlin/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
library/src/test/kotlin/com/chuckerteam/chucker/util/ChuckerInterceptorDelegate.kt
sample/src/main/kotlin/com/chuckerteam/chucker/sample/OkHttpUtils.kt

When `.skipPaths(".*(jpg|jpeg|png|gif|webp|svg|bmp|ico)$".toRegex())` is set
https://github.com/ChuckerTeam/chucker/assets/1086927/a22c0560-92f6-4662-a02a-6f480444995b
When `.skipDomain(".*akamai.com".toRegex(), "httpbin.org".toRegex())` is set
https://github.com/ChuckerTeam/chucker/assets/1086927/2268e059-5580-4c1c-b108-7ef5b7f398df
Fixes https://github.com/ChuckerTeam/chucker/issues/1236
* Added two new functions to [Builder](https://github.com/ChuckerTeam/chucker/blob/0527438f292dbdebe798e572106c8cf62687b8dc/library/src/main/kotlin/com/chuckerteam/chucker/api/ChuckerInterceptor.kt#L100)
* `skipPath(...Regex)`
* `skipDomain(...Regex)`
Check commmit eaff3e1c8c4f2a92e560852e400619117c6a8e02, and uncomment `skipPath` and/or `skipDomain` as needed.

Add Regex skipPath/skipDomain to Builder, fixes #1236

---

CHANGELOG.md
library/src/main/kotlin/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/main/kotlin/com/chuckerteam/chucker/internal/support/HttpUrlUtils.kt
library/src/test/kotlin/com/chuckerteam/chucker/api/ChuckerInterceptorSkipRequestTest.kt

The [Issue](https://github.com/ChuckerTeam/chucker/issues/1237) occurs when we add path segments delimited by '/' as part of the filtering mechanism, and HttpUrl treats them as a single, large path segment.
I added methods to safely add skips_path.
The problem with addPathSegments is that it replaces a leading '/' with an empty path segment, turning '/' into '//'. This causes issues for HttpUrl in general.
Both MockWebServer::url and HttpUrl.Builder::resolve don't handle '//' segments properly.
```kotlin
private fun executeRequestForPath(
okHttpClient: OkHttpClient,
path: String,
responseBody: String,
) {
val httpUrl =
HttpUrl.Builder()
.scheme("https")
.host("testexample.com")
.addPathSegments(path)
.build()
val request = Request.Builder().url(server.url(httpUrl.encodedPath)).build() …
```

Solution: method skipPaths on builder does not work as expected, issue #1237

---

library/src/main/kotlin/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadAdapter.kt
library/src/main/kotlin/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
library/src/main/res/drawable/chucker_ic_copy.xml
library/src/main/res/drawable/chucker_ic_copy_white.xml
library/src/main/res/layout/chucker_transaction_item_copy.xml
library/src/main/res/values-es/strings.xml
library/src/main/res/values-night/colors.xml
library/src/main/res/values/colors.xml
library/src/main/res/values/strings.xml

Fixes #1299
Added a button to copy the response

Implemented copy feature

---

library/build.gradle

None.
* Fixes https://github.com/ChuckerTeam/chucker/issues/1326
Move test dependency to test. How? Because `implementation` is auto-exposed to `testImplementation`, so it worked before. Moving it to test directly should still work.
* Introduced in https://github.com/ChuckerTeam/chucker/pull/1214
Removing a dependency is breaking change I guess, but since it was unintended it's not breaking?! idk 🤷🏻‍♂️
CI Should test it, tests should pass.
Release 4.1.1

Fix #1326: Move test dependency to test classpath

---

library/src/main/kotlin/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadAdapter.kt
library/src/main/kotlin/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt

This commit addresses and fixes the search functionality in the body ([issue reference](https://github.com/ChuckerTeam/chucker/issues/1334)) tab by:
- Including all items in the search instead of filtering only body line items.
- Correcting the index used for search and highlighting.
- Clearing spans when the query string is not found.
- Resetting highlight on all items.
These changes ensure that the search works correctly and highlights the correct lines in the body tab.
https://github.com/user-attachments/assets/e039c24f-cbd2-4a66-bd32-bb74629267d2

Fix: Search functionality in the body tab

---

library/src/test/kotlin/com/chuckerteam/chucker/internal/ui/MainViewModelTest.kt

|MainViewModel Unit Test Case |MainViewModel Unit Test Coverage |
|:---:|:---:|
|<img width="380" alt="Screenshot1" src="https://github.com/user-attachments/assets/ab4d897c-e1a5-444d-aa16-8865a4c87876">|<img width="380" alt="Screenshot1" src="https://github.com/user-attachments/assets/961c4c18-4606-40e7-80d5-8f1ef0c28efc">|
Add comprehensive unit tests for the MainViewModel to ensure proper functionality of transaction filtering, searching, and management.
Added new test class MainViewModelTest.kt with the following test coverage:
- Testing empty search query behavior
- Testing digit-only search query behavior
- Testing text search query behavior
- Testing getAllTransactions functionality
- Testing clearTransactions functionality
No breaking changes - This is a test-only addition

Test: Add unit tests for MainViewModel

---

library/src/main/kotlin/com/chuckerteam/chucker/internal/support/SearchHighlightUtil.kt

The `indicesOf` function in `SearchHighlightUtil` is refactored to use `Pattern.quote` for the search input. This ensures that any special characters in the search string are treated as literals, preventing potential `PatternSyntaxException`. In case a pattern cannot be compiled due to an invalid syntax a warning will be displayed in the logger and an empty list will be returned. Also we ensure the list is converted to immutable list to prevent unwanted modifications.
Fixes https://github.com/ChuckerTeam/chucker/issues/1341

Crash Fix: Handle PatternSyntaxException gracefully

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
library-no-op/build.gradle
library/build.gradle
library/src/main/kotlin/com/chuckerteam/chucker/internal/support/BitmapUtils.kt
library/src/main/kotlin/com/chuckerteam/chucker/internal/support/ChessboardDrawable.kt
library/src/main/kotlin/com/chuckerteam/chucker/internal/support/NotificationHelper.kt
library/src/main/kotlin/com/chuckerteam/chucker/internal/ui/MainViewModel.kt
sample/build.gradle

This commit updates the Gradle version and refactors lint configurations across multiple modules:
-   Updated the Android Gradle plugin version from `8.7.3` to `8.9.1` in the root `build.gradle` file.
-   Updated the Gradle wrapper to version `8.11.1` in `gradle-wrapper.properties`.
-   Replaced `lintOptions` with `lint` in the `library`, `sample`, and `library-no-op` modules.
-   Moved the `warningsAsErrors`, `abortOnError`, and `disable` configurations from `lintOptions` to `lint` in `library`, `sample` and `library-no-op`.
-   Applied the `disable 'RtlEnabled', 'GradleDependency'` to the `library`, and `library-no-op` modules.
-   Applied the `disable 'AcceptsUserCertificates', 'GradleDependency'` to the `sample` module.

Refactor: Update Gradle and lint configurations

---

build.gradle
sample/build.gradle
sample/src/androidTest/java/com/chuckerteam/chucker/sample/MainActivityTest.kt

https://github.com/user-attachments/assets/29ae7a5e-9ce7-4921-ba0b-ddf4142029eb
Added UI test coverage for the Chucker Sample App's `MainActivity` using Espresso. This helps verify the visibility and basic interaction of key UI components such as radio buttons and buttons that trigger HTTP/GraphQL activities.
- Created `MainActivityTest.kt` under `sample/src/androidTest/`
- Added tests to validate:
- Visibility of interceptor type selector
- Functionality of Application and Network radio buttons
- Presence and interaction with action buttons: HTTP, GraphQL, Launch Chucker, Export to Log/HAR
- Covered the screen shown in the launcher activity
No breaking changes introduced.
- Run the UI test with the following command:
```bash
./gradlew :sample:connectedAndroidTest
```
- Confirm that …

Added UI test case for main activity

---

sample/src/androidTest/java/com/chuckerteam/chucker/sample/ChuckerUITestLabels.kt
sample/src/androidTest/java/com/chuckerteam/chucker/sample/MainActivityTest.kt

📄 Context
This PR improves test coverage for the MainActivity by verifying the behavior and visibility of key buttons within the UI.
It ensures consistent interaction with elements like HTTP/GraphQL actions, Chucker launch, and export functionality, using the ChuckerUITestLabels constants to avoid hardcoded strings.
✨ Changes
✅ Added testButtonInteractions() to simulate tap on "DO HTTP ACTIVITY".
✅ Added testRadioButtonSelection() to check toggle behavior between "Application" and "Network" radio buttons.
✅ Added testHttpActivityButtonClick() to validate direct HTTP activity button action.
✅ Added testGraphQLActivityButtonClick() for GraphQL flow button.
✅ Added testLaunchChuckerDirectlyButtonClick() to confirm manual launch trigger works.
✅ Added testExportButtonsVisibility() to confirm …

Added More UI Tests and Created ChuckerUITestLabels for Reusability Test Strings

---

library/src/main/kotlin/com/chuckerteam/chucker/internal/data/repository/HttpTransactionDatabaseRepository.kt
library/src/main/kotlin/com/chuckerteam/chucker/internal/data/repository/HttpTransactionRepository.kt
library/src/main/kotlin/com/chuckerteam/chucker/internal/data/room/ChuckerDatabase.kt
library/src/main/kotlin/com/chuckerteam/chucker/internal/data/room/HttpTransactionDao.kt
library/src/main/kotlin/com/chuckerteam/chucker/internal/ui/MainActivity.kt
library/src/main/kotlin/com/chuckerteam/chucker/internal/ui/MainViewModel.kt
library/src/main/kotlin/com/chuckerteam/chucker/internal/ui/transaction/TransactionAdapter.kt
library/src/main/res/values-es/strings.xml
library/src/main/res/values-night/colors.xml
library/src/main/res/values-ru/strings.xml
library/src/main/res/values/colors.xml
library/src/main/res/values/strings.xml
library/src/test/kotlin/com/chuckerteam/chucker/internal/ui/MainViewModelTest.kt

|Light Mode | Dark Mode|
|:---:|:---:|
|<img width="380" alt="Screenshot1" src="https://github.com/user-attachments/assets/38d408cc-c381-415f-8d64-dd2164e9da84">|<img width="380" alt="Screenshot2" src="https://github.com/user-attachments/assets/9a56035f-fbc7-4d04-8729-c7f8fcffb717">|
Tested the flow - here is the testing video @cortinico 
https://github.com/user-attachments/assets/e236a4fc-14a0-455c-a2a7-2b500e8c510e
Issue link: https://github.com/ChuckerTeam/chucker/issues/1127
- Added multiple selection support in the transaction list.
- Used ID-based selection tracking for accurate and stable selection state.
- Applied selection highlight colour for both light and dark themes.
- Long-press any transaction to start selection mode.
- Tap additional items to select/deselect them.
- Verify …

Implement support for select multiple request

---

library/src/test/kotlin/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt

Fixing this lint failure that is making the CI be red.

Fix lint on ChuckerInterceptorTest

---

library/src/main/kotlin/com/chuckerteam/chucker/internal/data/room/ChuckerDatabase.kt

Replaces the deprecated fallbackToDestructiveMigration() call with the new overloaded method. This aligns with Room 2.7.2+ recommendations and removes deprecation warnings.
No visual changes. This is a code-only refactoring.
While exploring the codebase, I noticed that the `fallbackToDestructiveMigration()` method in `ChuckerDatabase.kt` is marked as deprecated in recent versions of AndroidX Room ([doc](https://developer.android.com/reference/androidx/room/RoomDatabase.Builder#fallbackToDestructiveMigration())). The official documentation recommends switching to the new overloaded method ([doc](https://developer.android.com/reference/androidx/room/RoomDatabase.Builder#fallbackToDestructiveMigration(kotlin.Boolean))).
Replaced the call to .fallbackToDestructiveMigration() with …

Refactor: Use modern Room migration API

---

build.gradle.kts

https://github.com/user-attachments/assets/468d6599-dc65-4d67-8932-cf693e5eae6d
This PR upgrades the `compileSdkVersion` and `targetSdkVersion` to API level 36, aligning the project with the latest Android SDK and enabling testing against the most recent platform behavior changes.
No related issue is currently linked.
- Updated compileSdk and targetSdk versions to 36 in the Gradle configuration files.
- Ensured compatibility by syncing and rebuilding the project successfully.
_No new features or UI changes were introduced. This is purely a build configuration upgrade._
None.
No breaking changes introduced.
- Run the sample app confirm nothing is broken.
- Validate that the app builds and runs as expected on Android 16 (API 34+) and emulators with API 36.
Monitor for any compatibility …

Upgrade target and compile SDK versions to 36
