build.gradle
library/build.gradle
library/src/main/java/com/readystatesoftware/chuck/internal/support/IOUtils.java
library/src/test/java/com/readystatesoftware/chuck/internal/support/IOUtilsTest.kt

- Configure unit tests
- Write a unit test to show the bug
- Fix the bug

Fix Issue #5 encoding not supported

---

gradle/wrapper/gradle-wrapper.properties

Time to modernize Gradle a bit 😅

Udpate Gradle version to 4.10.1

---

library/src/main/java/com/readystatesoftware/chuck/internal/ui/error/ErrorListFragment.java
library/src/main/java/com/readystatesoftware/chuck/internal/ui/transaction/TransactionListFragment.java
library/src/main/res/values/strings.xml

Show an AlertDialog when user try to delete HTTP calls or Errors to confirm his action.

Issue #43 Ask for confirmation when delete history

---

.github/ISSUE_TEMPLATE/bug_report.md
CHANGELOG.md
README.md
gradle.properties

Prepare 2.0.2

---

README.md

Looks like Artifactory is free for OSS projects, but there is an approval process to go through :/
I opted for JitPack as it was basically _configuration_ free.

Added Snapshots section to Readme

---

library/src/main/java/com/readystatesoftware/chuck/internal/support/NotificationHelper.java
library/src/main/java/com/readystatesoftware/chuck/internal/ui/transaction/TransactionAdapter.java
library/src/main/res/layout/chucker_list_item_transaction.xml
library/src/main/res/values/colors.xml
library/src/main/res/values/styles.xml
sample/src/main/res/values/colors.xml
sample/src/main/res/values/styles.xml

* Updating the color palette to use a darker blue
* Updated all the color references from `chuck` to `chucker`

Polishing the Color palette

---

README.md

Also added a couple of more badges (license + PRs are welcome).

Added Project Icon to Readme

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
library/build.gradle

Time to update some dependencies:
* Updating Kotlin to 1.3.11
* Updating to Gradle 5
* Updating OkHttp Dependencies

Updating Dependencies

---

README.md

So I've updated some things in the README that were out of date:
* Badges
* The project icon was missing
* Markdown styling
* Copyright notice

Updating the develop-branch README as was out of date

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
library/build.gradle
sample/build.gradle

I refactored the way how we organise deps versions. Now gradle plugin and production dependencies are together. Moreover I updated some versions.

Reorganize dependency versions

---

library/src/main/java/com/chuckerteam/chucker/api/internal/support/NotificationHelper.java

Fix for 'Push Notification is wrongly reporting the first HTTP request

---

library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt

- Adding missing KDoc for headersToRedact 55f6f5a
- Optimized imports for ChuckerInterceptor e76fa63

ChuckerInterceptor Cleanup

---

library/src/main/java/com/chuckerteam/chucker/api/internal/support/NotificationHelper.java

Access to `transactionBuffer` is not properly synchronized which may cause NPEs.
https://github.com/jgilfelt/chuck/issues/69

Fix race conditions in NotificationHelper.

---

library/src/main/java/com/chuckerteam/chucker/api/internal/ui/transaction/TransactionPayloadFragment.kt

Add search button on request tab

---

README.md

💌 Thanks @redwarp for helping the community by helping us to maintain Chucker.

Add Benoit Vermont to README Copyrights

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

---
name: Bug report
about: Create a report to help us improve
---
*A clear and concise description of what the bug is.*
*Steps to reproduce the behavior:*
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
*A clear and concise description of what you expected to happen.*
*If applicable, add screenshots to help explain your problem.*
- Device: *e.g. Nexus 6P*
- OS: *e.g. 7.1.1*
- Lib version: *e.g. 2.0.2*
*Add any other context about the problem here.*
---
---
name: Feature request
about: Suggest an idea for this project
---
*A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]*
*A clear and concise description of what you want to happen.*
*A clear and concise description of any alternative solutions or features you've …

Some pretty things in issue templates

---

.github/PULL_REQUEST_TEMPLATE

*Show us what you've changed, we love images.*
*Why did you changed something? Is there an [issue](https://github.com/ChuckerTeam/chucker/issues) to link here? Or an extarnal link?*
*Which code did you change? How?*
*PR that blocks this one, or the ones blocked by this PR*
*Is there something breaking in the API? Any class or method signature changed?*
*Is there a special case to test your changes?*
*Do we have to plan something else after the merge?*

Write Pull Request template

---

README.md

I added a chapter to thank our lovely contributor :heart: 
https://github.com/ChuckerTeam/chucker/tree/thanks_contributors#contributors

Add thanks to our contributors

---

library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/repository/HttpTransactionDatabaseRepository.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionActivity.kt

Cleanup kotlin classes

---

README.md

Let's add all the member of the ChuckerTeam to the README so that we're more approachable :) Also please welcome @vbuberen onboard 🎉👯🎆

Add ChuckerTeam to the README file

---

.github/PULL_REQUEST_TEMPLATE

Current pull request template contains some typos.
My changes fix them.

Fix for typos in PR template

---

README.md

Just adding the Slack Badge on the readme to make the chat easier to reach:

Udpate Chat Badge to #chucker on Kotlinlang slack

---

library/src/main/java/com/chuckerteam/chucker/internal/support/FormatUtils.kt

There were crashes during XML parsing #197 caused by unsupported attributes:
```
setAttribute("http://javax.xml.XMLConstants/property/accessExternalDTD", "")
setAttribute("http://javax.xml.XMLConstants/property/accessExternalStylesheet", "")
```
which were added in #39 
After some investigation found out that we can't just drop both of them on go on. Also, I found[ this doc](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.md#jaxp-documentbuilderfactory-saxparserfactory-and-dom4j) with some alternative methods to achieve the same result as with mentioned above attributes. Here is the screenshot with alternative attributes:
It requires switching to `DocumentBuilder` before creating `TransformerFactory`.
Unfortunately, we can use …

Fix for XML parsing

---

CHANGELOG.md
gradle.properties

Getting ready for the upcoming release. Let's wait for #197 and then we should be good to go.
Fixes #194

Prepare 3.1.0 stable

---

CHANGELOG.md
README.md

Updates for Readme and Changelog files.
Waiting for #206 to be merged and we are good to go.

Prepare 3.1.1

---

CHANGELOG.md
README.md
gradle.properties

Prepare 3.1.2

---

CHANGELOG.md

Looks like we haven't credit the last two messages, let's do it 👍

Add missing  section to release 3.1.1 and 3.1.2

---

.github/ISSUE_TEMPLATE/feature_request.md

Saw a typo in feature request Github template

Fix typo in feature request comment

---

build.gradle

Keeping Chucker up to date.
There were no breaking changes in updated dependencies, so we should be Ok.

Libs update

---

library/src/main/java/com/chuckerteam/chucker/api/ChuckerCollector.kt
library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/repository/HttpTransactionDatabaseRepository.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/repository/RecordedThrowableRepository.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/repository/RepositoryProvider.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/OkHttpUtils.kt
library/src/main/res/values/styles.xml
library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/OkHttpUtilsTest.kt

Fixed various lints.
- Fixed typos
- Fixed KDocs
- Removed unused code

Fixed various Lints

---

library/src/main/java/com/chuckerteam/chucker/internal/support/OkHttpUtils.kt

Removing outdated line with JVM Name.

Remove redundant JvmName

---

library-no-op/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt

I left some dead code in #279. 
Removed unnecessary mocking of `Context` method.
No.

Remove unnecessary mock method.

---

library/src/test/java/com/chuckerteam/chucker/internal/support/FormatUtilsTest.kt

added tests for `getShareCurlCommand()` method.

increased test coverage for class FormatUtils

---

library/src/test/java/com/chuckerteam/chucker/internal/support/FormatUtilsTest.kt

Added few test cases for JSON formatting.
- Added test case for invalid JSON.
- Added test case for JSON Array formatting.
No. All test cases are passing. No method signature change.

Added test cases for JSON formatting

---

CHANGELOG.md
README.md
gradle.properties

- Added changelogs for 3.2.0
- Bumped version
Would like to resolve discussion in #279 before proceeding with this release.

Prepare 3.2.0

---

build.gradle
library/build.gradle
library/src/main/java/com/chuckerteam/chucker/internal/support/BitmapUtils.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/ChessboardDrawable.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadAdapter.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
library/src/main/res/layout/chucker_transaction_item_image.xml
library/src/main/res/values/colors.xml
sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt

There is an issue. #319
Showing downloaded image preview triggers `Palette` to determine contrast colour based on the luminescence of the image. You can see in the screenshots that light image has dark background and vice versa.
One unfortunate thing is that `Palette` does not recognise alpha channel so we cannot filter out the the transparent background and `Palette` treats it as a black colour. What I do is I create a new bitmap that uses magenta in place of transparent pixels and then filter them out in the `Palette`. I chose magenta as it is rather a rare colour.
No.
I added image requests to the sample app. Unfortunately I didn't find any image generator that would operate on images with alpha and starting a local server just for that purpose seems too much.
Closes #319.

Image preview background contrast

---

build.gradle

Just bumping Kotlin to the latest patch version.

Kotlin to 1.3.72

---

gradle/gradle-mvn-push.gradle

I'm adding developer's information to the manifest.
@olivierperez I've copied over the data you added before
@vbuberen I've taken your email from your public git history in this repository. Please let me know if want to use another email.

Add missing developers to the manifest

---

build.gradle

Bumping Detekt to the latest stable
CI will tell the truth ✅

Detekt to 1.9.1

---

build.gradle
library-no-op/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt
library/src/main/java/com/chuckerteam/chucker/api/RetentionManager.kt
library/src/main/java/com/chuckerteam/chucker/internal/data/entity/HttpTransaction.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/ClearDatabaseService.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/FormatUtils.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/IOUtils.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/OkHttpUtils.kt
library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/MainViewModel.kt
library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt
library/src/test/java/com/chuckerteam/chucker/ChuckerInterceptorDelegate.kt
library/src/test/java/com/chuckerteam/chucker/TestUtils.kt
library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/IOUtilsTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/TeeSourceTest.kt
sample/src/main/java/com/chuckerteam/chucker/sample/HttpBinClient.kt

Bumping Ktlint to the latest stable.
I've run `ktlintFormat` on the whole codebase.
If the PR is green, we can merge 👍

KtLint to 0.37.0

---

build.gradle

In #423 tests that should fail passed. I want to to check if tests are correctly run on the CI.
I enabled logging output in the Gradle task.
#423 
No.
See the output of the CI console in the test step. https://github.com/ChuckerTeam/chucker/pull/424/checks?check_run_id=981509232#step:4:246

Log output of tests to the console

---

gradle/wrapper/gradle-wrapper.properties

Just bumping Gradle to the latest version.
n/a

Gradle to 6.6.1

---

build.gradle

Waited for Dependabot to take care of this update, but after 1 week decided to do it manually, since we are trying to move things towards soon release.
- Updated Kotlin to 1.4.10
Nothing

Kotlin to 1.4.10

---

README.md
gradle.properties

To move forward and have snapshots published we need to update version info.
- Updated version to `3.3.1-SNAPSHOT`.
- Updated Readme to mention updated version.
Decide how we proceed with development of 4.x versions.

Preparations for next versions

---

CHANGELOG.md
gradle.properties

Changes required for 3.4.0 release. Should be merged as soon as #491 is merged.
- Updated version name and version code
- Updated changelog
This PR should be merged after #491

Release 3.4.0

---

.github/workflows/publish-release.yaml

Just fixing a copy-pasta I did when setting up the publishing pipeline.

Update publishing action name

---

gradle.properties

Following up on #494, let's bump to `4.x` so we can start pushing on breaking changes.
- Updated version name and code for snapshot builds
- Updated readme file to actual versions

Prepare for the next major version

---

.github/dependabot.yml

Keeping Dependabot config up to date
Added @MiSikora as a reviewer for Dependabot PRs

Update list of reviewers for Dependabot

---

build.gradle

Updating dependency myself, since Dependabot can't pick the right version
- Update Coroutines to 1.4.2

Update Coroutines to 1.4.2

---

build.gradle
library/src/main/java/com/chuckerteam/chucker/api/RetentionManager.kt
library/src/test/java/com/chuckerteam/chucker/TestTransactionFactory.kt
library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt

- Updated Ktlint to 0.40.0
- Updated formatting in some files to match updated rules

Update Ktlint to 0.40.0

---

build.gradle

Updated Lifecycle myself, since was curios about some changes in [2.3.0](https://developer.android.com/jetpack/androidx/releases/lifecycle#version_230_3)
- Updated Lifecycle to 2.3.0
Nothing breaking

Update Lifecycle to 2.3.0

---

build.gradle

- Bump versions for solving build failed with this PR [Bump fragment-ktx from 1.3.0 to 1.3.1](https://github.com/ChuckerTeam/chucker/pull/577)

Bump activity & fragment versions

---

library/src/main/java/com/chuckerteam/chucker/api/Chucker.kt

Detekt reported nesting issue.
I refactored creating shortcut function.
No.
No functional changes so the shortcut should behave in the same way.
N/A

Reduce cyclomatic complexity of creating shortcut

---

CHANGELOG.md

Added info that Chucker now creates shortcuts

Mention shortcuts in the changelog

---

library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorDecodingTest.kt
library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/data/entity/HttpTransactionTupleTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/data/repository/HttpTransactionDatabaseRepositoryTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/data/repository/RepositoryProviderTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/data/room/HttpTransactionDaoTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/DepletingSourceTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/FileFactoryTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/FormatUtilsTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/FormattedUrlTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/JsonConverterTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/LimitingSourceTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/LiveDataCombineLatestTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/LiveDataDistinctUntilChangedTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/OkHttpUtilsTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/OkioUtilsTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/ReportingSinkTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/TeeSourceTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/TransactionCurlCommandSharableTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/TransactionDetailsSharableTest.kt
library/src/test/java/com/chuckerteam/chucker/internal/support/TransactionListDetailsSharableTest.kt

There is an issue – #442.
I renamed tests using backtics.
No.
Rely on CI.
Closes #442.

Use backticks in test names

---

build.gradle
gradle/kotlin-static-analysis.gradle
gradle/wrapper/gradle-wrapper.properties
library/build.gradle

[Gradle 7.0](https://docs.gradle.org/7.0/release-notes.html) is a big release, many features come.
- Bump gradle to 7.0
- Bump other versions
- Remove `coroutines-core` as `coroutines-android` api it

Update Gradle to 7.0

---

gradle/gradle-mvn-push.gradle

We forgot to add MiSikora as a developer in POM file. This change happened on `3.x` branch already to have him mentioned in 3.5.0 release. Now adding here, so we have him in future releases.

Update developers list in POM file

---

build.gradle
gradle.properties

Changes for 3.5.1 release. Mainly dependencies updates.
Update readme and changelogs, but it will be in another PR.

Release 3.5.1

---

CHANGELOG.md
README.md
build.gradle
gradle.properties

Minor updates to dependencies and preparation for 3.5.2 to re-deploy missed aar file.

Release 3.5.2

---

CHANGELOG.md
README.md

Update changelogs for 3.5.2 release

---

build.gradle

Bumping targetSDK and compileSDK as the library was ready for this already.

Bump target and compile SDK to 31

---

.github/FUNDING.yml

Adding the Sponsor ❤️ button to the Chucker repository 🎉

Setup Sponsor Button

---

README.md

Add information about sponsorship to the README file

Add sponsorship information

---

.github/dependabot.yml
README.md
gradle/gradle-mvn-push.gradle

Not much to elaborate on. Unfortunately, I don't have much capacity for this project anymore. :(

Remove self from project maintainers

---

CHANGELOG.md

We had several entries in the changelog missing + some of them had missing issues/pr references. I'm polishing them up.
n/a

Cleanup the Changelog file

---

gradle.properties

Getting ready to prepare a new stable release.

Prepare Chucker 4.0.0

---

CHANGELOG.md
README.md
gradle.properties

Just updating the README and other necessary bits post 4.0.0 release.
I'm also setting the version to `4.1.0-SNAPSHOT`

Update readme for 4.0.0 release

---

build.gradle

This reverts commit 3e078d4022a5313167dc24288a91a203f0218dbf.

Revert "Bump kotlinVersion from 2.0.21 to 2.1.0 (#1317)"

---

CHANGELOG.md
gradle.properties

Time for a new Chucker minor release! 🚀

Prepare Chucker 4.1.0

---

library/src/test/kotlin/com/chuckerteam/chucker/internal/InstantExecutorExtension.kt
library/src/test/kotlin/com/chuckerteam/chucker/internal/ui/transaction/TransactionViewModelTest.kt

|TransactionViewModel Unit Test Case |
|:---:|
|<img width="380" alt="Screenshot1" src="https://github.com/user-attachments/assets/88a188e3-04e0-4bbe-b152-a573410be8da">|
Add comprehensive unit tests for the TransactionViewModel to ensure proper functionality
No breaking changes - This is a test-only addition

Add Unit test cases for TransactionViewModel

---

sample/src/main/kotlin/com/chuckerteam/chucker/sample/GraphQlTask.kt

https://github.com/user-attachments/assets/13c83e98-397a-4a6f-8e2b-d330dfb00311
The sample app’s `GraphQlTask` was crashing whenever the Apollo client’s `.execute()` call encountered a network-unavailable error. This change ensures that network failures are caught and logged rather than crashing the app 
Scoped coroutines: Replaced the previous MainScope() with a custom
```
CoroutineScope(
SupervisorJob() +
Dispatchers.IO +
CoroutineExceptionHandler { _, error ->
Log.e("NetworkScope", "Unexpected error", error)
}
)
```
to isolate failures and log them.
Error handling: Wrapped the suspended calls
```
api.getCharacterById(...).execute()
apolloClient.query(...).execute()
```
inside a `supervisorScope { async { … } }` and consumed their results with `runCatching { … }` so that any IOException …

fix: handle Apollo no-network error to prevent crash
